# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'WIFIS.ui'
#
# Created by: PyQt5 UI code generator 5.8.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(893, 770)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 811, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 811, 39))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(0, 40, 811, 161))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.groupBox = QtWidgets.QGroupBox(self.horizontalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(10, 30, 31, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(10, 50, 31, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(10, 70, 31, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(10, 90, 31, 16))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setGeometry(QtCore.QRect(10, 110, 31, 16))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setGeometry(QtCore.QRect(10, 130, 31, 16))
        self.label_7.setObjectName("label_7")
        self.RALabel = QtWidgets.QLabel(self.groupBox)
        self.RALabel.setGeometry(QtCore.QRect(50, 30, 101, 16))
        self.RALabel.setObjectName("RALabel")
        self.DECLabel = QtWidgets.QLabel(self.groupBox)
        self.DECLabel.setGeometry(QtCore.QRect(50, 50, 121, 16))
        self.DECLabel.setObjectName("DECLabel")
        self.AZLabel = QtWidgets.QLabel(self.groupBox)
        self.AZLabel.setGeometry(QtCore.QRect(50, 70, 121, 16))
        self.AZLabel.setObjectName("AZLabel")
        self.ELLabel = QtWidgets.QLabel(self.groupBox)
        self.ELLabel.setGeometry(QtCore.QRect(50, 90, 121, 16))
        self.ELLabel.setObjectName("ELLabel")
        self.IISLabel = QtWidgets.QLabel(self.groupBox)
        self.IISLabel.setGeometry(QtCore.QRect(50, 110, 121, 16))
        self.IISLabel.setObjectName("IISLabel")
        self.HALabel = QtWidgets.QLabel(self.groupBox)
        self.HALabel.setGeometry(QtCore.QRect(50, 130, 121, 16))
        self.HALabel.setObjectName("HALabel")
        self.label_2.raise_()
        self.label_3.raise_()
        self.label_4.raise_()
        self.label_5.raise_()
        self.label_6.raise_()
        self.label_7.raise_()
        self.RALabel.raise_()
        self.DECLabel.raise_()
        self.AZLabel.raise_()
        self.ELLabel.raise_()
        self.IISLabel.raise_()
        self.HALabel.raise_()
        self.horizontalLayout_3.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setAutoFillBackground(False)
        self.groupBox_2.setCheckable(False)
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_8 = QtWidgets.QLabel(self.groupBox_2)
        self.label_8.setGeometry(QtCore.QRect(10, 30, 71, 21))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.groupBox_2)
        self.label_9.setGeometry(QtCore.QRect(10, 60, 81, 21))
        self.label_9.setObjectName("label_9")
        self.RAMoveBox = QtWidgets.QTextEdit(self.groupBox_2)
        self.RAMoveBox.setGeometry(QtCore.QRect(100, 30, 61, 21))
        self.RAMoveBox.setPlaceholderText("")
        self.RAMoveBox.setObjectName("RAMoveBox")
        self.DECMoveBox = QtWidgets.QTextEdit(self.groupBox_2)
        self.DECMoveBox.setGeometry(QtCore.QRect(100, 60, 61, 21))
        self.DECMoveBox.setObjectName("DECMoveBox")
        self.moveTelescopeButton = QtWidgets.QPushButton(self.groupBox_2)
        self.moveTelescopeButton.setGeometry(QtCore.QRect(20, 80, 131, 31))
        self.moveTelescopeButton.setObjectName("moveTelescopeButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_2.setGeometry(QtCore.QRect(180, 30, 131, 31))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_3.setGeometry(QtCore.QRect(180, 60, 131, 32))
        self.pushButton_3.setObjectName("pushButton_3")
        self.groupBox.raise_()
        self.groupBox.raise_()
        self.label_8.raise_()
        self.label_9.raise_()
        self.RAMoveBox.raise_()
        self.DECMoveBox.raise_()
        self.moveTelescopeButton.raise_()
        self.pushButton_2.raise_()
        self.pushButton_3.raise_()
        self.horizontalLayout_3.addWidget(self.groupBox_2)
        self.groupBox_6 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_6.setGeometry(QtCore.QRect(0, 200, 809, 141))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.groupBox_6.setFont(font)
        self.groupBox_6.setObjectName("groupBox_6")
        self.textEdit = QtWidgets.QTextEdit(self.groupBox_6)
        self.textEdit.setGeometry(QtCore.QRect(80, 30, 171, 21))
        self.textEdit.setObjectName("textEdit")
        self.label_14 = QtWidgets.QLabel(self.groupBox_6)
        self.label_14.setGeometry(QtCore.QRect(10, 30, 60, 21))
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.groupBox_6)
        self.label_15.setGeometry(QtCore.QRect(10, 60, 60, 21))
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.groupBox_6)
        self.label_16.setGeometry(QtCore.QRect(10, 90, 60, 21))
        self.label_16.setObjectName("label_16")
        self.textEdit_2 = QtWidgets.QTextEdit(self.groupBox_6)
        self.textEdit_2.setGeometry(QtCore.QRect(80, 60, 171, 21))
        self.textEdit_2.setObjectName("textEdit_2")
        self.textEdit_3 = QtWidgets.QTextEdit(self.groupBox_6)
        self.textEdit_3.setGeometry(QtCore.QRect(80, 90, 171, 21))
        self.textEdit_3.setObjectName("textEdit_3")
        self.pushButton = QtWidgets.QPushButton(self.groupBox_6)
        self.pushButton.setGeometry(QtCore.QRect(250, 50, 121, 32))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setDefault(False)
        self.pushButton.setFlat(False)
        self.pushButton.setObjectName("pushButton")
        self.label_17 = QtWidgets.QLabel(self.groupBox_6)
        self.label_17.setGeometry(QtCore.QRect(400, 30, 71, 21))
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.groupBox_6)
        self.label_18.setGeometry(QtCore.QRect(400, 60, 71, 21))
        self.label_18.setObjectName("label_18")
        self.textEdit_4 = QtWidgets.QTextEdit(self.groupBox_6)
        self.textEdit_4.setGeometry(QtCore.QRect(460, 30, 121, 21))
        self.textEdit_4.setObjectName("textEdit_4")
        self.textEdit_5 = QtWidgets.QTextEdit(self.groupBox_6)
        self.textEdit_5.setGeometry(QtCore.QRect(460, 60, 121, 21))
        self.textEdit_5.setObjectName("textEdit_5")
        self.label_19 = QtWidgets.QLabel(self.groupBox_6)
        self.label_19.setGeometry(QtCore.QRect(400, 100, 71, 16))
        self.label_19.setObjectName("label_19")
        self.radioButton = QtWidgets.QRadioButton(self.groupBox_6)
        self.radioButton.setGeometry(QtCore.QRect(470, 90, 100, 20))
        self.radioButton.setChecked(True)
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(self.groupBox_6)
        self.radioButton_2.setGeometry(QtCore.QRect(470, 110, 100, 20))
        self.radioButton_2.setObjectName("radioButton_2")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(0, 340, 811, 361))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox_4 = QtWidgets.QGroupBox(self.widget)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.groupBox_4.setFont(font)
        self.groupBox_4.setObjectName("groupBox_4")
        self.label_20 = QtWidgets.QLabel(self.groupBox_4)
        self.label_20.setGeometry(QtCore.QRect(10, 30, 60, 21))
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(self.groupBox_4)
        self.label_21.setGeometry(QtCore.QRect(10, 60, 60, 21))
        self.label_21.setObjectName("label_21")
        self.textEdit_6 = QtWidgets.QTextEdit(self.groupBox_4)
        self.textEdit_6.setGeometry(QtCore.QRect(80, 30, 61, 21))
        self.textEdit_6.setObjectName("textEdit_6")
        self.textEdit_7 = QtWidgets.QTextEdit(self.groupBox_4)
        self.textEdit_7.setGeometry(QtCore.QRect(80, 60, 61, 21))
        self.textEdit_7.setObjectName("textEdit_7")
        self.label_20.raise_()
        self.label_21.raise_()
        self.textEdit_6.raise_()
        self.textEdit_7.raise_()
        self.groupBox_6.raise_()
        self.verticalLayout.addWidget(self.groupBox_4)
        self.groupBox_5 = QtWidgets.QGroupBox(self.widget)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.groupBox_5.setFont(font)
        self.groupBox_5.setObjectName("groupBox_5")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.groupBox_5)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(170, 20, 141, 151))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_26 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_26.setFont(font)
        self.label_26.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_26.setObjectName("label_26")
        self.verticalLayout_2.addWidget(self.label_26)
        self.label_33 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_33.setFont(font)
        self.label_33.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_33.setObjectName("label_33")
        self.verticalLayout_2.addWidget(self.label_33)
        self.label_25 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_25.setFont(font)
        self.label_25.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_25.setObjectName("label_25")
        self.verticalLayout_2.addWidget(self.label_25)
        self.label_27 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_27.setFont(font)
        self.label_27.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_27.setObjectName("label_27")
        self.verticalLayout_2.addWidget(self.label_27)
        self.label_28 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_28.setFont(font)
        self.label_28.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_28.setObjectName("label_28")
        self.verticalLayout_2.addWidget(self.label_28)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.groupBox_5)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(320, 20, 160, 151))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.ExpType = QtWidgets.QComboBox(self.verticalLayoutWidget_2)
        self.ExpType.setObjectName("ExpType")
        self.ExpType.addItem("")
        self.ExpType.addItem("")
        self.verticalLayout_4.addWidget(self.ExpType)
        self.ExpTime = QtWidgets.QTextEdit(self.verticalLayoutWidget_2)
        self.ExpTime.setObjectName("ExpTime")
        self.verticalLayout_4.addWidget(self.ExpTime)
        self.CCDObject = QtWidgets.QTextEdit(self.verticalLayoutWidget_2)
        self.CCDObject.setObjectName("CCDObject")
        self.verticalLayout_4.addWidget(self.CCDObject)
        self.CCDTemp = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.CCDTemp.setObjectName("CCDTemp")
        self.verticalLayout_4.addWidget(self.CCDTemp)
        self.SetTempValue = QtWidgets.QTextEdit(self.verticalLayoutWidget_2)
        self.SetTempValue.setObjectName("SetTempValue")
        self.verticalLayout_4.addWidget(self.SetTempValue)
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.groupBox_5)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(480, 20, 130, 151))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.SaveImageButton = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.SaveImageButton.setObjectName("SaveImageButton")
        self.verticalLayout_5.addWidget(self.SaveImageButton)
        self.FocusCameraButton = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.FocusCameraButton.setObjectName("FocusCameraButton")
        self.verticalLayout_5.addWidget(self.FocusCameraButton)
        self.CentroidButton = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.CentroidButton.setObjectName("CentroidButton")
        self.verticalLayout_5.addWidget(self.CentroidButton)
        self.SetTempButton = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.SetTempButton.setObjectName("SetTempButton")
        self.verticalLayout_5.addWidget(self.SetTempButton)
        self.SaveImageButton_2 = QtWidgets.QPushButton(self.groupBox_5)
        self.SaveImageButton_2.setGeometry(QtCore.QRect(660, 20, 130, 32))
        self.SaveImageButton_2.setObjectName("SaveImageButton_2")
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.groupBox_5)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(0, 30, 74, 111))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_22 = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.verticalLayout_6.addWidget(self.label_22)
        self.label_23 = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_23.setFont(font)
        self.label_23.setObjectName("label_23")
        self.verticalLayout_6.addWidget(self.label_23)
        self.label_24 = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_24.setFont(font)
        self.label_24.setObjectName("label_24")
        self.verticalLayout_6.addWidget(self.label_24)
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.groupBox_5)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(20, 140, 141, 31))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.BKWButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.BKWButton.setObjectName("BKWButton")
        self.horizontalLayout_4.addWidget(self.BKWButton)
        self.FWDButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.FWDButton.setObjectName("FWDButton")
        self.horizontalLayout_4.addWidget(self.FWDButton)
        self.verticalLayoutWidget_5 = QtWidgets.QWidget(self.groupBox_5)
        self.verticalLayoutWidget_5.setGeometry(QtCore.QRect(80, 30, 104, 111))
        self.verticalLayoutWidget_5.setObjectName("verticalLayoutWidget_5")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_5)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.FilterVal = QtWidgets.QComboBox(self.verticalLayoutWidget_5)
        self.FilterVal.setObjectName("FilterVal")
        self.FilterVal.addItem("")
        self.FilterVal.addItem("")
        self.FilterVal.addItem("")
        self.FilterVal.addItem("")
        self.FilterVal.addItem("")
        self.verticalLayout_7.addWidget(self.FilterVal)
        self.FocPosition = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.FocPosition.sizePolicy().hasHeightForWidth())
        self.FocPosition.setSizePolicy(sizePolicy)
        self.FocPosition.setObjectName("FocPosition")
        self.verticalLayout_7.addWidget(self.FocPosition)
        self.textEdit_8 = QtWidgets.QTextEdit(self.verticalLayoutWidget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEdit_8.sizePolicy().hasHeightForWidth())
        self.textEdit_8.setSizePolicy(sizePolicy)
        self.textEdit_8.setMaximumSize(QtCore.QSize(16777215, 25))
        self.textEdit_8.setObjectName("textEdit_8")
        self.verticalLayout_7.addWidget(self.textEdit_8)
        self.verticalLayoutWidget.raise_()
        self.verticalLayoutWidget_2.raise_()
        self.verticalLayoutWidget_3.raise_()
        self.SaveImageButton_2.raise_()
        self.verticalLayoutWidget_4.raise_()
        self.horizontalLayoutWidget_3.raise_()
        self.FocPosition.raise_()
        self.verticalLayoutWidget_5.raise_()
        self.verticalLayout.addWidget(self.groupBox_5)
        self.horizontalLayoutWidget.raise_()
        self.horizontalLayoutWidget.raise_()
        self.label.raise_()
        self.horizontalLayoutWidget_2.raise_()
        self.groupBox_4.raise_()
        self.groupBox_5.raise_()
        self.groupBox_6.raise_()
        self.groupBox_4.raise_()
        self.groupBox_4.raise_()
        self.groupBox_4.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 893, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuPower = QtWidgets.QMenu(self.menubar)
        self.menuPower.setObjectName("menuPower")
        self.menuInitialie = QtWidgets.QMenu(self.menubar)
        self.menuInitialie.setObjectName("menuInitialie")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuPower.menuAction())
        self.menubar.addAction(self.menuInitialie.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "WIFIS Control"))
        self.groupBox.setTitle(_translate("MainWindow", "Telescope Parameters"))
        self.label_2.setText(_translate("MainWindow", "RA"))
        self.label_3.setText(_translate("MainWindow", "DEC"))
        self.label_4.setText(_translate("MainWindow", "AZ"))
        self.label_5.setText(_translate("MainWindow", "EL"))
        self.label_6.setText(_translate("MainWindow", "IIS"))
        self.label_7.setText(_translate("MainWindow", "HA"))
        self.RALabel.setText(_translate("MainWindow", "TextLabel"))
        self.DECLabel.setText(_translate("MainWindow", "TextLabel"))
        self.AZLabel.setText(_translate("MainWindow", "TextLabel"))
        self.ELLabel.setText(_translate("MainWindow", "TextLabel"))
        self.IISLabel.setText(_translate("MainWindow", "TextLabel"))
        self.HALabel.setText(_translate("MainWindow", "TextLabel"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Telescope Control"))
        self.label_8.setText(_translate("MainWindow", "RA Move (\")"))
        self.label_9.setText(_translate("MainWindow", "DEC Move (\")"))
        self.RAMoveBox.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'.SF NS Text\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">0</p></body></html>"))
        self.DECMoveBox.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'.SF NS Text\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">0</p></body></html>"))
        self.moveTelescopeButton.setText(_translate("MainWindow", "Adjust Telescope"))
        self.pushButton_2.setText(_translate("MainWindow", "Move To Guider"))
        self.pushButton_3.setText(_translate("MainWindow", "Move to WIFIS"))
        self.groupBox_6.setTitle(_translate("MainWindow", "Source Parameters"))
        self.label_14.setText(_translate("MainWindow", "Object:"))
        self.label_15.setText(_translate("MainWindow", "RA Obj:"))
        self.label_16.setText(_translate("MainWindow", "DEC Obj:"))
        self.pushButton.setText(_translate("MainWindow", "Move to Object"))
        self.label_17.setText(_translate("MainWindow", "Nod RA:"))
        self.label_18.setText(_translate("MainWindow", "Nod DEC:"))
        self.label_19.setText(_translate("MainWindow", "Nod Type:"))
        self.radioButton.setText(_translate("MainWindow", "Offset (\")"))
        self.radioButton_2.setText(_translate("MainWindow", "Pos RA/DEC"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Exposure Control"))
        self.label_20.setText(_translate("MainWindow", "N Ramps:"))
        self.label_21.setText(_translate("MainWindow", "N Reads:"))
        self.groupBox_5.setTitle(_translate("MainWindow", "Guider Control"))
        self.label_26.setText(_translate("MainWindow", "Exposure Type:"))
        self.label_33.setText(_translate("MainWindow", "Exposure Time (ms):"))
        self.label_25.setText(_translate("MainWindow", "Camera Object:"))
        self.label_27.setText(_translate("MainWindow", "CCD Temp:"))
        self.label_28.setText(_translate("MainWindow", "Temp"))
        self.ExpType.setCurrentText(_translate("MainWindow", "Normal"))
        self.ExpType.setItemText(0, _translate("MainWindow", "Normal"))
        self.ExpType.setItemText(1, _translate("MainWindow", "Dark"))
        self.CCDTemp.setText(_translate("MainWindow", "TextLabel"))
        self.SaveImageButton.setText(_translate("MainWindow", "Save Image"))
        self.FocusCameraButton.setText(_translate("MainWindow", "Focus Camera"))
        self.CentroidButton.setText(_translate("MainWindow", "Centroid Stars"))
        self.SetTempButton.setText(_translate("MainWindow", "Set Temp"))
        self.SaveImageButton_2.setText(_translate("MainWindow", "Take Image"))
        self.label_22.setText(_translate("MainWindow", "Filter:"))
        self.label_23.setText(_translate("MainWindow", "Focus Pos:"))
        self.label_24.setText(_translate("MainWindow", "Focus Step:"))
        self.BKWButton.setText(_translate("MainWindow", "BWD"))
        self.FWDButton.setText(_translate("MainWindow", "FWD"))
        self.FilterVal.setCurrentText(_translate("MainWindow", "Z"))
        self.FilterVal.setItemText(0, _translate("MainWindow", "Z"))
        self.FilterVal.setItemText(1, _translate("MainWindow", "I"))
        self.FilterVal.setItemText(2, _translate("MainWindow", "R"))
        self.FilterVal.setItemText(3, _translate("MainWindow", "G"))
        self.FilterVal.setItemText(4, _translate("MainWindow", "H-Alpha"))
        self.FocPosition.setText(_translate("MainWindow", "TextLabel"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuPower.setTitle(_translate("MainWindow", "Power"))
        self.menuInitialie.setTitle(_translate("MainWindow", "Initialize"))

