# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'WIFIS.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(950, 859)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(0, 20))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget_6 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_6.setGeometry(QtCore.QRect(0, 0, 917, 801))
        self.verticalLayoutWidget_6.setObjectName("verticalLayoutWidget_6")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_6)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget_6)
        self.label.setMinimumSize(QtCore.QSize(0, 40))
        self.label.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        self.line_7 = QtWidgets.QFrame(self.verticalLayoutWidget_6)
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.verticalLayout_3.addWidget(self.line_7)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.gridLayout.setObjectName("gridLayout")
        self.IISLabel = QtWidgets.QLabel(self.verticalLayoutWidget_6)
        self.IISLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.IISLabel.setObjectName("IISLabel")
        self.gridLayout.addWidget(self.IISLabel, 6, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.verticalLayoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 0, 0, 1, 2)
        self.label_5 = QtWidgets.QLabel(self.verticalLayoutWidget_6)
        self.label_5.setMaximumSize(QtCore.QSize(40, 16777215))
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 4, 0, 1, 1)
        self.DECLabel = QtWidgets.QLabel(self.verticalLayoutWidget_6)
        self.DECLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.DECLabel.setObjectName("DECLabel")
        self.gridLayout.addWidget(self.DECLabel, 3, 1, 1, 1)
        self.HALabel = QtWidgets.QLabel(self.verticalLayoutWidget_6)
        self.HALabel.setAlignment(QtCore.Qt.AlignCenter)
        self.HALabel.setObjectName("HALabel")
        self.gridLayout.addWidget(self.HALabel, 7, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.verticalLayoutWidget_6)
        self.label_6.setMaximumSize(QtCore.QSize(40, 16777215))
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 6, 0, 1, 1)
        self.ELLabel = QtWidgets.QLabel(self.verticalLayoutWidget_6)
        self.ELLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.ELLabel.setObjectName("ELLabel")
        self.gridLayout.addWidget(self.ELLabel, 4, 1, 1, 1)
        self.AZLabel = QtWidgets.QLabel(self.verticalLayoutWidget_6)
        self.AZLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.AZLabel.setObjectName("AZLabel")
        self.gridLayout.addWidget(self.AZLabel, 5, 1, 1, 1)
        self.RALabel = QtWidgets.QLabel(self.verticalLayoutWidget_6)
        self.RALabel.setAlignment(QtCore.Qt.AlignCenter)
        self.RALabel.setObjectName("RALabel")
        self.gridLayout.addWidget(self.RALabel, 2, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget_6)
        self.label_2.setMaximumSize(QtCore.QSize(40, 16777215))
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.verticalLayoutWidget_6)
        self.label_7.setMaximumSize(QtCore.QSize(40, 16777215))
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 7, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget_6)
        self.label_4.setMaximumSize(QtCore.QSize(40, 16777215))
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 5, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget_6)
        self.label_3.setMaximumSize(QtCore.QSize(40, 16777215))
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 3, 0, 1, 1)
        self.horizontalLayout_3.addLayout(self.gridLayout)
        self.line_4 = QtWidgets.QFrame(self.verticalLayoutWidget_6)
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.horizontalLayout_3.addWidget(self.line_4)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_8 = QtWidgets.QLabel(self.verticalLayoutWidget_6)
        self.label_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 1, 0, 1, 1)
        self.WIFISMoveButton = QtWidgets.QPushButton(self.verticalLayoutWidget_6)
        self.WIFISMoveButton.setObjectName("WIFISMoveButton")
        self.gridLayout_2.addWidget(self.WIFISMoveButton, 2, 2, 1, 1)
        self.RAMoveBox = QtWidgets.QTextEdit(self.verticalLayoutWidget_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RAMoveBox.sizePolicy().hasHeightForWidth())
        self.RAMoveBox.setSizePolicy(sizePolicy)
        self.RAMoveBox.setMaximumSize(QtCore.QSize(16777215, 20))
        self.RAMoveBox.setProperty("placeholderText", "")
        self.RAMoveBox.setObjectName("RAMoveBox")
        self.gridLayout_2.addWidget(self.RAMoveBox, 1, 1, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.verticalLayoutWidget_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy)
        self.label_11.setMinimumSize(QtCore.QSize(0, 10))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.gridLayout_2.addWidget(self.label_11, 0, 0, 1, 3)
        self.GuiderMoveButton = QtWidgets.QPushButton(self.verticalLayoutWidget_6)
        self.GuiderMoveButton.setObjectName("GuiderMoveButton")
        self.gridLayout_2.addWidget(self.GuiderMoveButton, 1, 2, 1, 1)
        self.DECMoveBox = QtWidgets.QTextEdit(self.verticalLayoutWidget_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DECMoveBox.sizePolicy().hasHeightForWidth())
        self.DECMoveBox.setSizePolicy(sizePolicy)
        self.DECMoveBox.setMaximumSize(QtCore.QSize(16777215, 20))
        self.DECMoveBox.setObjectName("DECMoveBox")
        self.gridLayout_2.addWidget(self.DECMoveBox, 2, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.verticalLayoutWidget_6)
        self.label_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 2, 0, 1, 1)
        self.moveTelescopeButton = QtWidgets.QPushButton(self.verticalLayoutWidget_6)
        self.moveTelescopeButton.setObjectName("moveTelescopeButton")
        self.gridLayout_2.addWidget(self.moveTelescopeButton, 3, 1, 1, 1)
        self.horizontalLayout_3.addLayout(self.gridLayout_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.line = QtWidgets.QFrame(self.verticalLayoutWidget_6)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_3.addWidget(self.line)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_12 = QtWidgets.QLabel(self.verticalLayoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.gridLayout_3.addWidget(self.label_12, 0, 0, 1, 8)
        self.RAObj = QtWidgets.QTextEdit(self.verticalLayoutWidget_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RAObj.sizePolicy().hasHeightForWidth())
        self.RAObj.setSizePolicy(sizePolicy)
        self.RAObj.setMaximumSize(QtCore.QSize(16777215, 30))
        self.RAObj.setObjectName("RAObj")
        self.gridLayout_3.addWidget(self.RAObj, 2, 1, 1, 1)
        self.DECObj = QtWidgets.QTextEdit(self.verticalLayoutWidget_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DECObj.sizePolicy().hasHeightForWidth())
        self.DECObj.setSizePolicy(sizePolicy)
        self.DECObj.setMaximumSize(QtCore.QSize(16777215, 30))
        self.DECObj.setObjectName("DECObj")
        self.gridLayout_3.addWidget(self.DECObj, 3, 1, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.verticalLayoutWidget_6)
        self.label_15.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_15.setObjectName("label_15")
        self.gridLayout_3.addWidget(self.label_15, 2, 0, 1, 1)
        self.NodDecText = QtWidgets.QTextEdit(self.verticalLayoutWidget_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.NodDecText.sizePolicy().hasHeightForWidth())
        self.NodDecText.setSizePolicy(sizePolicy)
        self.NodDecText.setMaximumSize(QtCore.QSize(16777215, 30))
        self.NodDecText.setObjectName("NodDecText")
        self.gridLayout_3.addWidget(self.NodDecText, 2, 4, 1, 1)
        self.ObjText = QtWidgets.QTextEdit(self.verticalLayoutWidget_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ObjText.sizePolicy().hasHeightForWidth())
        self.ObjText.setSizePolicy(sizePolicy)
        self.ObjText.setMinimumSize(QtCore.QSize(0, 20))
        self.ObjText.setMaximumSize(QtCore.QSize(16777215, 30))
        self.ObjText.setObjectName("ObjText")
        self.gridLayout_3.addWidget(self.ObjText, 1, 1, 1, 1)
        self.label_32 = QtWidgets.QLabel(self.verticalLayoutWidget_6)
        self.label_32.setObjectName("label_32")
        self.gridLayout_3.addWidget(self.label_32, 3, 6, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.verticalLayoutWidget_6)
        self.label_16.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_16.setObjectName("label_16")
        self.gridLayout_3.addWidget(self.label_16, 3, 0, 1, 1)
        self.NodRAText = QtWidgets.QTextEdit(self.verticalLayoutWidget_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.NodRAText.sizePolicy().hasHeightForWidth())
        self.NodRAText.setSizePolicy(sizePolicy)
        self.NodRAText.setMaximumSize(QtCore.QSize(16777215, 30))
        self.NodRAText.setObjectName("NodRAText")
        self.gridLayout_3.addWidget(self.NodRAText, 1, 4, 1, 1)
        self.line_6 = QtWidgets.QFrame(self.verticalLayoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.line_6.setFont(font)
        self.line_6.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.gridLayout_3.addWidget(self.line_6, 1, 5, 3, 1)
        self.label_17 = QtWidgets.QLabel(self.verticalLayoutWidget_6)
        self.label_17.setObjectName("label_17")
        self.gridLayout_3.addWidget(self.label_17, 1, 3, 1, 1)
        self.SetNextButton = QtWidgets.QPushButton(self.verticalLayoutWidget_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SetNextButton.sizePolicy().hasHeightForWidth())
        self.SetNextButton.setSizePolicy(sizePolicy)
        self.SetNextButton.setDefault(False)
        self.SetNextButton.setFlat(False)
        self.SetNextButton.setObjectName("SetNextButton")
        self.gridLayout_3.addWidget(self.SetNextButton, 2, 2, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.verticalLayoutWidget_6)
        self.label_14.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_14.setObjectName("label_14")
        self.gridLayout_3.addWidget(self.label_14, 1, 0, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.verticalLayoutWidget_6)
        self.label_19.setObjectName("label_19")
        self.gridLayout_3.addWidget(self.label_19, 3, 3, 1, 1)
        self.NNods_2 = QtWidgets.QTextEdit(self.verticalLayoutWidget_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.NNods_2.sizePolicy().hasHeightForWidth())
        self.NNods_2.setSizePolicy(sizePolicy)
        self.NNods_2.setMaximumSize(QtCore.QSize(16777215, 30))
        self.NNods_2.setObjectName("NNods_2")
        self.gridLayout_3.addWidget(self.NNods_2, 3, 7, 1, 1)
        self.NodSelection = QtWidgets.QComboBox(self.verticalLayoutWidget_6)
        self.NodSelection.setObjectName("NodSelection")
        self.NodSelection.addItem("")
        self.NodSelection.addItem("")
        self.gridLayout_3.addWidget(self.NodSelection, 1, 7, 1, 1)
        self.label_31 = QtWidgets.QLabel(self.verticalLayoutWidget_6)
        self.label_31.setObjectName("label_31")
        self.gridLayout_3.addWidget(self.label_31, 2, 6, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.OffsetNod = QtWidgets.QRadioButton(self.verticalLayoutWidget_6)
        self.OffsetNod.setChecked(True)
        self.OffsetNod.setObjectName("OffsetNod")
        self.verticalLayout.addWidget(self.OffsetNod)
        self.RADECNod = QtWidgets.QRadioButton(self.verticalLayoutWidget_6)
        self.RADECNod.setObjectName("RADECNod")
        self.verticalLayout.addWidget(self.RADECNod)
        self.gridLayout_3.addLayout(self.verticalLayout, 3, 4, 1, 1)
        self.NNods = QtWidgets.QTextEdit(self.verticalLayoutWidget_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.NNods.sizePolicy().hasHeightForWidth())
        self.NNods.setSizePolicy(sizePolicy)
        self.NNods.setMaximumSize(QtCore.QSize(16777215, 30))
        self.NNods.setObjectName("NNods")
        self.gridLayout_3.addWidget(self.NNods, 2, 7, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.verticalLayoutWidget_6)
        self.label_18.setObjectName("label_18")
        self.gridLayout_3.addWidget(self.label_18, 2, 3, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.verticalLayoutWidget_6)
        self.label_25.setObjectName("label_25")
        self.gridLayout_3.addWidget(self.label_25, 1, 6, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout_3)
        self.line_2 = QtWidgets.QFrame(self.verticalLayoutWidget_6)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_3.addWidget(self.line_2)
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_30 = QtWidgets.QLabel(self.verticalLayoutWidget_6)
        self.label_30.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_30.setObjectName("label_30")
        self.gridLayout_5.addWidget(self.label_30, 3, 0, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.verticalLayoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setAutoFillBackground(False)
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.gridLayout_5.addWidget(self.label_13, 0, 0, 1, 5)
        self.label_21 = QtWidgets.QLabel(self.verticalLayoutWidget_6)
        self.label_21.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_21.setObjectName("label_21")
        self.gridLayout_5.addWidget(self.label_21, 2, 0, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.verticalLayoutWidget_6)
        self.label_20.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_20.setObjectName("label_20")
        self.gridLayout_5.addWidget(self.label_20, 1, 0, 1, 1)
        self.NRampsText = QtWidgets.QTextEdit(self.verticalLayoutWidget_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.NRampsText.sizePolicy().hasHeightForWidth())
        self.NRampsText.setSizePolicy(sizePolicy)
        self.NRampsText.setMinimumSize(QtCore.QSize(0, 0))
        self.NRampsText.setMaximumSize(QtCore.QSize(16777215, 30))
        self.NRampsText.setObjectName("NRampsText")
        self.gridLayout_5.addWidget(self.NRampsText, 1, 1, 1, 1)
        self.NReadsTExt = QtWidgets.QTextEdit(self.verticalLayoutWidget_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.NReadsTExt.sizePolicy().hasHeightForWidth())
        self.NReadsTExt.setSizePolicy(sizePolicy)
        self.NReadsTExt.setMaximumSize(QtCore.QSize(16777215, 30))
        self.NReadsTExt.setObjectName("NReadsTExt")
        self.gridLayout_5.addWidget(self.NReadsTExt, 2, 1, 1, 1)
        self.label_34 = QtWidgets.QLabel(self.verticalLayoutWidget_6)
        self.label_34.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_34.setObjectName("label_34")
        self.gridLayout_5.addWidget(self.label_34, 1, 2, 1, 1)
        self.ExpTypeSelect = QtWidgets.QComboBox(self.verticalLayoutWidget_6)
        self.ExpTypeSelect.setObjectName("ExpTypeSelect")
        self.ExpTypeSelect.addItem("")
        self.ExpTypeSelect.addItem("")
        self.ExpTypeSelect.addItem("")
        self.ExpTypeSelect.addItem("")
        self.ExpTypeSelect.addItem("")
        self.gridLayout_5.addWidget(self.ExpTypeSelect, 1, 3, 1, 1)
        self.ExposureButton = QtWidgets.QPushButton(self.verticalLayoutWidget_6)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.ExposureButton.setFont(font)
        self.ExposureButton.setObjectName("ExposureButton")
        self.gridLayout_5.addWidget(self.ExposureButton, 2, 3, 1, 1)
        self.NodBeginButton = QtWidgets.QPushButton(self.verticalLayoutWidget_6)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.NodBeginButton.setFont(font)
        self.NodBeginButton.setObjectName("NodBeginButton")
        self.gridLayout_5.addWidget(self.NodBeginButton, 1, 4, 1, 1)
        self.StopExpButton = QtWidgets.QPushButton(self.verticalLayoutWidget_6)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.StopExpButton.setFont(font)
        self.StopExpButton.setObjectName("StopExpButton")
        self.gridLayout_5.addWidget(self.StopExpButton, 2, 4, 1, 1)
        self.ExpProgressBar = QtWidgets.QProgressBar(self.verticalLayoutWidget_6)
        self.ExpProgressBar.setProperty("value", 24)
        self.ExpProgressBar.setObjectName("ExpProgressBar")
        self.gridLayout_5.addWidget(self.ExpProgressBar, 3, 1, 1, 4)
        self.TakeCalibButton = QtWidgets.QPushButton(self.verticalLayoutWidget_6)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.TakeCalibButton.setFont(font)
        self.TakeCalibButton.setObjectName("TakeCalibButton")
        self.gridLayout_5.addWidget(self.TakeCalibButton, 2, 2, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout_5)
        self.line_3 = QtWidgets.QFrame(self.verticalLayoutWidget_6)
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.line_3.setFont(font)
        self.line_3.setAutoFillBackground(False)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout_3.addWidget(self.line_3)
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.SaveImageButton = QtWidgets.QPushButton(self.verticalLayoutWidget_6)
        self.SaveImageButton.setObjectName("SaveImageButton")
        self.gridLayout_6.addWidget(self.SaveImageButton, 3, 6, 1, 1)
        self.line_5 = QtWidgets.QFrame(self.verticalLayoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.line_5.setFont(font)
        self.line_5.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.gridLayout_6.addWidget(self.line_5, 3, 3, 4, 1)
        self.SetTempButton = QtWidgets.QPushButton(self.verticalLayoutWidget_6)
        self.SetTempButton.setObjectName("SetTempButton")
        self.gridLayout_6.addWidget(self.SetTempButton, 6, 6, 1, 1)
        self.label_26 = QtWidgets.QLabel(self.verticalLayoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_26.setFont(font)
        self.label_26.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_26.setObjectName("label_26")
        self.gridLayout_6.addWidget(self.label_26, 3, 4, 1, 1)
        self.TakeImageButton = QtWidgets.QPushButton(self.verticalLayoutWidget_6)
        self.TakeImageButton.setObjectName("TakeImageButton")
        self.gridLayout_6.addWidget(self.TakeImageButton, 3, 7, 1, 1)
        self.CentroidButton = QtWidgets.QPushButton(self.verticalLayoutWidget_6)
        self.CentroidButton.setObjectName("CentroidButton")
        self.gridLayout_6.addWidget(self.CentroidButton, 5, 6, 1, 1)
        self.label_33 = QtWidgets.QLabel(self.verticalLayoutWidget_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_33.sizePolicy().hasHeightForWidth())
        self.label_33.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_33.setFont(font)
        self.label_33.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_33.setObjectName("label_33")
        self.gridLayout_6.addWidget(self.label_33, 4, 4, 1, 1)
        self.ExpType = QtWidgets.QComboBox(self.verticalLayoutWidget_6)
        self.ExpType.setObjectName("ExpType")
        self.ExpType.addItem("")
        self.ExpType.addItem("")
        self.gridLayout_6.addWidget(self.ExpType, 3, 5, 1, 1)
        self.ExpTime = QtWidgets.QTextEdit(self.verticalLayoutWidget_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ExpTime.sizePolicy().hasHeightForWidth())
        self.ExpTime.setSizePolicy(sizePolicy)
        self.ExpTime.setMaximumSize(QtCore.QSize(16777215, 30))
        self.ExpTime.setObjectName("ExpTime")
        self.gridLayout_6.addWidget(self.ExpTime, 4, 5, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.verticalLayoutWidget_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_23.sizePolicy().hasHeightForWidth())
        self.label_23.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_23.setFont(font)
        self.label_23.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_23.setObjectName("label_23")
        self.gridLayout_6.addWidget(self.label_23, 4, 1, 1, 1)
        self.FocPosition = QtWidgets.QLabel(self.verticalLayoutWidget_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.FocPosition.sizePolicy().hasHeightForWidth())
        self.FocPosition.setSizePolicy(sizePolicy)
        self.FocPosition.setObjectName("FocPosition")
        self.gridLayout_6.addWidget(self.FocPosition, 4, 2, 1, 1)
        self.SetTempValue = QtWidgets.QTextEdit(self.verticalLayoutWidget_6)
        self.SetTempValue.setObjectName("SetTempValue")
        self.gridLayout_6.addWidget(self.SetTempValue, 6, 5, 1, 1)
        self.FilterVal = QtWidgets.QComboBox(self.verticalLayoutWidget_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.FilterVal.sizePolicy().hasHeightForWidth())
        self.FilterVal.setSizePolicy(sizePolicy)
        self.FilterVal.setObjectName("FilterVal")
        self.FilterVal.addItem("")
        self.FilterVal.addItem("")
        self.FilterVal.addItem("")
        self.FilterVal.addItem("")
        self.FilterVal.addItem("")
        self.gridLayout_6.addWidget(self.FilterVal, 3, 2, 1, 1)
        self.label_28 = QtWidgets.QLabel(self.verticalLayoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_28.setFont(font)
        self.label_28.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_28.setObjectName("label_28")
        self.gridLayout_6.addWidget(self.label_28, 6, 4, 1, 1)
        self.StartGuidingButton = QtWidgets.QPushButton(self.verticalLayoutWidget_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.StartGuidingButton.sizePolicy().hasHeightForWidth())
        self.StartGuidingButton.setSizePolicy(sizePolicy)
        self.StartGuidingButton.setObjectName("StartGuidingButton")
        self.gridLayout_6.addWidget(self.StartGuidingButton, 4, 7, 1, 1)
        self.FocusCameraButton = QtWidgets.QPushButton(self.verticalLayoutWidget_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.FocusCameraButton.sizePolicy().hasHeightForWidth())
        self.FocusCameraButton.setSizePolicy(sizePolicy)
        self.FocusCameraButton.setObjectName("FocusCameraButton")
        self.gridLayout_6.addWidget(self.FocusCameraButton, 4, 6, 1, 1)
        self.label_27 = QtWidgets.QLabel(self.verticalLayoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_27.setFont(font)
        self.label_27.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_27.setObjectName("label_27")
        self.gridLayout_6.addWidget(self.label_27, 5, 4, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.verticalLayoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_24.setFont(font)
        self.label_24.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_24.setObjectName("label_24")
        self.gridLayout_6.addWidget(self.label_24, 5, 1, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.BKWButton = QtWidgets.QPushButton(self.verticalLayoutWidget_6)
        self.BKWButton.setObjectName("BKWButton")
        self.horizontalLayout.addWidget(self.BKWButton)
        self.FWDButton = QtWidgets.QPushButton(self.verticalLayoutWidget_6)
        self.FWDButton.setObjectName("FWDButton")
        self.horizontalLayout.addWidget(self.FWDButton)
        self.gridLayout_6.addLayout(self.horizontalLayout, 6, 1, 1, 1)
        self.CCDTemp = QtWidgets.QLabel(self.verticalLayoutWidget_6)
        self.CCDTemp.setObjectName("CCDTemp")
        self.gridLayout_6.addWidget(self.CCDTemp, 5, 5, 1, 1)
        self.FocStep = QtWidgets.QTextEdit(self.verticalLayoutWidget_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.FocStep.sizePolicy().hasHeightForWidth())
        self.FocStep.setSizePolicy(sizePolicy)
        self.FocStep.setMaximumSize(QtCore.QSize(16777215, 25))
        self.FocStep.setObjectName("FocStep")
        self.gridLayout_6.addWidget(self.FocStep, 5, 2, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.verticalLayoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_22.setFont(font)
        self.label_22.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_22.setObjectName("label_22")
        self.gridLayout_6.addWidget(self.label_22, 3, 1, 1, 1)
        self.label_29 = QtWidgets.QLabel(self.verticalLayoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_29.setFont(font)
        self.label_29.setAlignment(QtCore.Qt.AlignCenter)
        self.label_29.setObjectName("label_29")
        self.gridLayout_6.addWidget(self.label_29, 2, 1, 1, 7)
        self.verticalLayout_3.addLayout(self.gridLayout_6)
        self.verticalLayoutWidget_6.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 950, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuPower = QtWidgets.QMenu(self.menubar)
        self.menuPower.setObjectName("menuPower")
        self.menuInitialie = QtWidgets.QMenu(self.menubar)
        self.menuInitialie.setObjectName("menuInitialie")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionConnect = QtWidgets.QAction(MainWindow)
        self.actionConnect.setObjectName("actionConnect")
        self.actionInitialize = QtWidgets.QAction(MainWindow)
        self.actionInitialize.setObjectName("actionInitialize")
        self.actionDisconnect = QtWidgets.QAction(MainWindow)
        self.actionDisconnect.setObjectName("actionDisconnect")
        self.menuInitialie.addAction(self.actionConnect)
        self.menuInitialie.addAction(self.actionInitialize)
        self.menuInitialie.addAction(self.actionDisconnect)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuPower.menuAction())
        self.menubar.addAction(self.menuInitialie.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "WIFIS Control"))
        self.IISLabel.setText(_translate("MainWindow", "TextLabel"))
        self.label_10.setText(_translate("MainWindow", "Telescope Parameters"))
        self.label_5.setText(_translate("MainWindow", "EL:"))
        self.DECLabel.setText(_translate("MainWindow", "TextLabel"))
        self.HALabel.setText(_translate("MainWindow", "TextLabel"))
        self.label_6.setText(_translate("MainWindow", "IIS:"))
        self.ELLabel.setText(_translate("MainWindow", "TextLabel"))
        self.AZLabel.setText(_translate("MainWindow", "TextLabel"))
        self.RALabel.setText(_translate("MainWindow", "TextLabel"))
        self.label_2.setText(_translate("MainWindow", "RA:"))
        self.label_7.setText(_translate("MainWindow", "HA:"))
        self.label_4.setText(_translate("MainWindow", "AZ:"))
        self.label_3.setText(_translate("MainWindow", "DEC:"))
        self.label_8.setText(_translate("MainWindow", "RA Move (\")"))
        self.WIFISMoveButton.setText(_translate("MainWindow", "Move to WIFIS"))
        self.RAMoveBox.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'.SF NS Text\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">0</p></body></html>"))
        self.label_11.setText(_translate("MainWindow", "Telescope Control"))
        self.GuiderMoveButton.setText(_translate("MainWindow", "Move To Guider"))
        self.DECMoveBox.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'.SF NS Text\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">0</p></body></html>"))
        self.label_9.setText(_translate("MainWindow", "DEC Move (\")"))
        self.moveTelescopeButton.setText(_translate("MainWindow", "Adjust Telescope"))
        self.label_12.setText(_translate("MainWindow", "Source Parameters"))
        self.label_15.setText(_translate("MainWindow", "RA Obj:"))
        self.label_32.setText(_translate("MainWindow", "Nods per Cal"))
        self.label_16.setText(_translate("MainWindow", "DEC Obj:"))
        self.label_17.setText(_translate("MainWindow", "Nod RA:"))
        self.SetNextButton.setText(_translate("MainWindow", "Set Object as Next"))
        self.label_14.setText(_translate("MainWindow", "Object:"))
        self.label_19.setText(_translate("MainWindow", "Nod Type:"))
        self.NNods_2.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'.SF NS Text\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">3</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.NodSelection.setItemText(0, _translate("MainWindow", "ABA"))
        self.NodSelection.setItemText(1, _translate("MainWindow", "AB"))
        self.label_31.setText(_translate("MainWindow", "N Nods"))
        self.OffsetNod.setText(_translate("MainWindow", "Offset (\")"))
        self.RADECNod.setText(_translate("MainWindow", "Pos RA/DEC"))
        self.NNods.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'.SF NS Text\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">1</p></body></html>"))
        self.label_18.setText(_translate("MainWindow", "Nod DEC:"))
        self.label_25.setText(_translate("MainWindow", "Nod Pattern"))
        self.label_30.setText(_translate("MainWindow", "Exp Progress"))
        self.label_13.setText(_translate("MainWindow", "Exposure Control"))
        self.label_21.setText(_translate("MainWindow", "N Reads:"))
        self.label_20.setText(_translate("MainWindow", "N Ramps:"))
        self.NRampsText.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'.SF NS Text\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">1</p></body></html>"))
        self.NReadsTExt.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'.SF NS Text\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">200</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.label_34.setText(_translate("MainWindow", "Exposure Type:"))
        self.ExpTypeSelect.setItemText(0, _translate("MainWindow", "Ramp"))
        self.ExpTypeSelect.setItemText(1, _translate("MainWindow", "CDS"))
        self.ExpTypeSelect.setItemText(2, _translate("MainWindow", "Single Frame"))
        self.ExpTypeSelect.setItemText(3, _translate("MainWindow", "Arc Ramp"))
        self.ExpTypeSelect.setItemText(4, _translate("MainWindow", "Flat Ramp"))
        self.ExposureButton.setText(_translate("MainWindow", "EXPOSURE"))
        self.NodBeginButton.setText(_translate("MainWindow", "BEGIN NOD SEQ"))
        self.StopExpButton.setText(_translate("MainWindow", "STOP EXPOSURE"))
        self.TakeCalibButton.setText(_translate("MainWindow", "Take Calib"))
        self.SaveImageButton.setText(_translate("MainWindow", "Save Image"))
        self.SetTempButton.setText(_translate("MainWindow", "Set Temp"))
        self.label_26.setText(_translate("MainWindow", "Exposure Type:"))
        self.TakeImageButton.setText(_translate("MainWindow", "Take Image"))
        self.CentroidButton.setText(_translate("MainWindow", "Centroid Stars"))
        self.label_33.setText(_translate("MainWindow", "Exposure Time (ms):"))
        self.ExpType.setProperty("currentText", _translate("MainWindow", "Normal"))
        self.ExpType.setItemText(0, _translate("MainWindow", "Normal"))
        self.ExpType.setItemText(1, _translate("MainWindow", "Dark"))
        self.label_23.setText(_translate("MainWindow", "Focus Pos:"))
        self.FocPosition.setText(_translate("MainWindow", "TextLabel"))
        self.FilterVal.setProperty("currentText", _translate("MainWindow", "Z"))
        self.FilterVal.setItemText(0, _translate("MainWindow", "Z"))
        self.FilterVal.setItemText(1, _translate("MainWindow", "I"))
        self.FilterVal.setItemText(2, _translate("MainWindow", "R"))
        self.FilterVal.setItemText(3, _translate("MainWindow", "G"))
        self.FilterVal.setItemText(4, _translate("MainWindow", "H-Alpha"))
        self.label_28.setText(_translate("MainWindow", "Set CCD Temp"))
        self.StartGuidingButton.setText(_translate("MainWindow", "Start Guiding"))
        self.FocusCameraButton.setText(_translate("MainWindow", "Focus Camera"))
        self.label_27.setText(_translate("MainWindow", "CCD Temp:"))
        self.label_24.setText(_translate("MainWindow", "Focus Step:"))
        self.BKWButton.setText(_translate("MainWindow", "BWD"))
        self.FWDButton.setText(_translate("MainWindow", "FWD"))
        self.CCDTemp.setText(_translate("MainWindow", "TextLabel"))
        self.label_22.setText(_translate("MainWindow", "Filter:"))
        self.label_29.setText(_translate("MainWindow", "Guider Control"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuPower.setTitle(_translate("MainWindow", "Power"))
        self.menuInitialie.setTitle(_translate("MainWindow", "H2RG"))
        self.actionConnect.setText(_translate("MainWindow", "Connect"))
        self.actionConnect.setToolTip(_translate("MainWindow", "Connect to H2RG Server"))
        self.actionInitialize.setText(_translate("MainWindow", "Initialize"))
        self.actionInitialize.setToolTip(_translate("MainWindow", "Initialize H2RG Detector"))
        self.actionDisconnect.setText(_translate("MainWindow", "Disconnect"))
        self.actionDisconnect.setToolTip(_translate("MainWindow", "Disconnect from H2RG Server"))

