# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'WIFIS.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(980, 932)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(0, 20))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.gridLayout_10 = QtWidgets.QGridLayout()
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setMaximumSize(QtCore.QSize(40, 16777215))
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.IISLabel = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.IISLabel.sizePolicy().hasHeightForWidth())
        self.IISLabel.setSizePolicy(sizePolicy)
        self.IISLabel.setMinimumSize(QtCore.QSize(200, 0))
        self.IISLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.IISLabel.setObjectName("IISLabel")
        self.gridLayout.addWidget(self.IISLabel, 6, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setMaximumSize(QtCore.QSize(40, 16777215))
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 4, 0, 1, 1)
        self.RALabel = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RALabel.sizePolicy().hasHeightForWidth())
        self.RALabel.setSizePolicy(sizePolicy)
        self.RALabel.setMinimumSize(QtCore.QSize(200, 0))
        self.RALabel.setAlignment(QtCore.Qt.AlignCenter)
        self.RALabel.setObjectName("RALabel")
        self.gridLayout.addWidget(self.RALabel, 2, 1, 1, 1)
        self.DECLabel = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DECLabel.sizePolicy().hasHeightForWidth())
        self.DECLabel.setSizePolicy(sizePolicy)
        self.DECLabel.setMinimumSize(QtCore.QSize(200, 0))
        self.DECLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.DECLabel.setObjectName("DECLabel")
        self.gridLayout.addWidget(self.DECLabel, 3, 1, 1, 1)
        self.HALabel = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.HALabel.sizePolicy().hasHeightForWidth())
        self.HALabel.setSizePolicy(sizePolicy)
        self.HALabel.setMinimumSize(QtCore.QSize(200, 0))
        self.HALabel.setAlignment(QtCore.Qt.AlignCenter)
        self.HALabel.setObjectName("HALabel")
        self.gridLayout.addWidget(self.HALabel, 7, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 0, 0, 1, 2)
        self.ELLabel = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ELLabel.sizePolicy().hasHeightForWidth())
        self.ELLabel.setSizePolicy(sizePolicy)
        self.ELLabel.setMinimumSize(QtCore.QSize(200, 0))
        self.ELLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.ELLabel.setObjectName("ELLabel")
        self.gridLayout.addWidget(self.ELLabel, 4, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setMaximumSize(QtCore.QSize(40, 16777215))
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 6, 0, 1, 1)
        self.AZLabel = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.AZLabel.sizePolicy().hasHeightForWidth())
        self.AZLabel.setSizePolicy(sizePolicy)
        self.AZLabel.setMinimumSize(QtCore.QSize(200, 0))
        self.AZLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.AZLabel.setObjectName("AZLabel")
        self.gridLayout.addWidget(self.AZLabel, 5, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setMaximumSize(QtCore.QSize(40, 16777215))
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 7, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setMaximumSize(QtCore.QSize(40, 16777215))
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 5, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setMaximumSize(QtCore.QSize(40, 16777215))
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 3, 0, 1, 1)
        self.horizontalLayout_3.addLayout(self.gridLayout)
        self.line_4 = QtWidgets.QFrame(self.centralwidget)
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.horizontalLayout_3.addWidget(self.line_4)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_7.setContentsMargins(10, 0, 10, 0)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout_2.setContentsMargins(0, -1, -1, -1)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_9 = QtWidgets.QLabel(self.tab)
        self.label_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 1, 0, 1, 1)
        self.label_36 = QtWidgets.QLabel(self.tab)
        self.label_36.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_36.setObjectName("label_36")
        self.gridLayout_2.addWidget(self.label_36, 0, 4, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.tab)
        self.label_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 0, 0, 1, 1)
        self.WIFISMoveButton = QtWidgets.QPushButton(self.tab)
        self.WIFISMoveButton.setObjectName("WIFISMoveButton")
        self.gridLayout_2.addWidget(self.WIFISMoveButton, 1, 2, 1, 1)
        self.label_35 = QtWidgets.QLabel(self.tab)
        self.label_35.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_35.setObjectName("label_35")
        self.gridLayout_2.addWidget(self.label_35, 1, 4, 1, 1)
        self.MoveBackButton = QtWidgets.QPushButton(self.tab)
        self.MoveBackButton.setObjectName("MoveBackButton")
        self.gridLayout_2.addWidget(self.MoveBackButton, 2, 2, 1, 1)
        self.CalOffsetButton = QtWidgets.QPushButton(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CalOffsetButton.sizePolicy().hasHeightForWidth())
        self.CalOffsetButton.setSizePolicy(sizePolicy)
        self.CalOffsetButton.setMinimumSize(QtCore.QSize(0, 0))
        self.CalOffsetButton.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.CalOffsetButton.setObjectName("CalOffsetButton")
        self.gridLayout_2.addWidget(self.CalOffsetButton, 2, 5, 1, 1)
        self.RAMoveBox = QtWidgets.QLineEdit(self.tab)
        self.RAMoveBox.setObjectName("RAMoveBox")
        self.gridLayout_2.addWidget(self.RAMoveBox, 0, 1, 1, 1)
        self.GuiderMoveButton = QtWidgets.QPushButton(self.tab)
        self.GuiderMoveButton.setObjectName("GuiderMoveButton")
        self.gridLayout_2.addWidget(self.GuiderMoveButton, 0, 2, 1, 1)
        self.YPos = QtWidgets.QLineEdit(self.tab)
        self.YPos.setObjectName("YPos")
        self.gridLayout_2.addWidget(self.YPos, 1, 5, 1, 1)
        self.moveTelescopeButton = QtWidgets.QPushButton(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.moveTelescopeButton.sizePolicy().hasHeightForWidth())
        self.moveTelescopeButton.setSizePolicy(sizePolicy)
        self.moveTelescopeButton.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.moveTelescopeButton.setObjectName("moveTelescopeButton")
        self.gridLayout_2.addWidget(self.moveTelescopeButton, 2, 1, 1, 1)
        self.XPos = QtWidgets.QLineEdit(self.tab)
        self.XPos.setObjectName("XPos")
        self.gridLayout_2.addWidget(self.XPos, 0, 5, 1, 1)
        self.DECMoveBox = QtWidgets.QLineEdit(self.tab)
        self.DECMoveBox.setObjectName("DECMoveBox")
        self.gridLayout_2.addWidget(self.DECMoveBox, 1, 1, 1, 1)
        self.CenteringCheck = QtWidgets.QPushButton(self.tab)
        self.CenteringCheck.setObjectName("CenteringCheck")
        self.gridLayout_2.addWidget(self.CenteringCheck, 3, 2, 1, 1)
        self.line_8 = QtWidgets.QFrame(self.tab)
        self.line_8.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.gridLayout_2.addWidget(self.line_8, 0, 3, 4, 1)
        self.gridLayout_7.addLayout(self.gridLayout_2, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_9.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.gridLayout_8 = QtWidgets.QGridLayout()
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.Power15 = QtWidgets.QPushButton(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Power15.sizePolicy().hasHeightForWidth())
        self.Power15.setSizePolicy(sizePolicy)
        self.Power15.setObjectName("Power15")
        self.gridLayout_8.addWidget(self.Power15, 1, 1, 1, 1)
        self.Power23 = QtWidgets.QPushButton(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Power23.sizePolicy().hasHeightForWidth())
        self.Power23.setSizePolicy(sizePolicy)
        self.Power23.setObjectName("Power23")
        self.gridLayout_8.addWidget(self.Power23, 3, 2, 1, 1)
        self.Power24 = QtWidgets.QPushButton(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Power24.sizePolicy().hasHeightForWidth())
        self.Power24.setSizePolicy(sizePolicy)
        self.Power24.setObjectName("Power24")
        self.gridLayout_8.addWidget(self.Power24, 4, 2, 1, 1)
        self.Power27 = QtWidgets.QPushButton(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Power27.sizePolicy().hasHeightForWidth())
        self.Power27.setSizePolicy(sizePolicy)
        self.Power27.setObjectName("Power27")
        self.gridLayout_8.addWidget(self.Power27, 3, 3, 1, 1)
        self.Power11 = QtWidgets.QPushButton(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Power11.sizePolicy().hasHeightForWidth())
        self.Power11.setSizePolicy(sizePolicy)
        self.Power11.setObjectName("Power11")
        self.gridLayout_8.addWidget(self.Power11, 1, 0, 1, 1)
        self.Power13 = QtWidgets.QPushButton(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Power13.sizePolicy().hasHeightForWidth())
        self.Power13.setSizePolicy(sizePolicy)
        self.Power13.setObjectName("Power13")
        self.gridLayout_8.addWidget(self.Power13, 3, 0, 1, 1)
        self.Power12 = QtWidgets.QPushButton(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Power12.sizePolicy().hasHeightForWidth())
        self.Power12.setSizePolicy(sizePolicy)
        self.Power12.setObjectName("Power12")
        self.gridLayout_8.addWidget(self.Power12, 2, 0, 1, 1)
        self.Power17 = QtWidgets.QPushButton(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Power17.sizePolicy().hasHeightForWidth())
        self.Power17.setSizePolicy(sizePolicy)
        self.Power17.setObjectName("Power17")
        self.gridLayout_8.addWidget(self.Power17, 3, 1, 1, 1)
        self.Power25 = QtWidgets.QPushButton(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Power25.sizePolicy().hasHeightForWidth())
        self.Power25.setSizePolicy(sizePolicy)
        self.Power25.setObjectName("Power25")
        self.gridLayout_8.addWidget(self.Power25, 1, 3, 1, 1)
        self.Power22 = QtWidgets.QPushButton(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Power22.sizePolicy().hasHeightForWidth())
        self.Power22.setSizePolicy(sizePolicy)
        self.Power22.setObjectName("Power22")
        self.gridLayout_8.addWidget(self.Power22, 2, 2, 1, 1)
        self.Power26 = QtWidgets.QPushButton(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Power26.sizePolicy().hasHeightForWidth())
        self.Power26.setSizePolicy(sizePolicy)
        self.Power26.setObjectName("Power26")
        self.gridLayout_8.addWidget(self.Power26, 2, 3, 1, 1)
        self.Power28 = QtWidgets.QPushButton(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Power28.sizePolicy().hasHeightForWidth())
        self.Power28.setSizePolicy(sizePolicy)
        self.Power28.setObjectName("Power28")
        self.gridLayout_8.addWidget(self.Power28, 4, 3, 1, 1)
        self.Power21 = QtWidgets.QPushButton(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Power21.sizePolicy().hasHeightForWidth())
        self.Power21.setSizePolicy(sizePolicy)
        self.Power21.setObjectName("Power21")
        self.gridLayout_8.addWidget(self.Power21, 1, 2, 1, 1)
        self.Power16 = QtWidgets.QPushButton(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Power16.sizePolicy().hasHeightForWidth())
        self.Power16.setSizePolicy(sizePolicy)
        self.Power16.setObjectName("Power16")
        self.gridLayout_8.addWidget(self.Power16, 2, 1, 1, 1)
        self.Power18 = QtWidgets.QPushButton(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Power18.sizePolicy().hasHeightForWidth())
        self.Power18.setSizePolicy(sizePolicy)
        self.Power18.setObjectName("Power18")
        self.gridLayout_8.addWidget(self.Power18, 4, 1, 1, 1)
        self.Power14 = QtWidgets.QPushButton(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Power14.sizePolicy().hasHeightForWidth())
        self.Power14.setSizePolicy(sizePolicy)
        self.Power14.setObjectName("Power14")
        self.gridLayout_8.addWidget(self.Power14, 4, 0, 1, 1)
        self.label_38 = QtWidgets.QLabel(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_38.sizePolicy().hasHeightForWidth())
        self.label_38.setSizePolicy(sizePolicy)
        self.label_38.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_38.setFont(font)
        self.label_38.setAlignment(QtCore.Qt.AlignCenter)
        self.label_38.setObjectName("label_38")
        self.gridLayout_8.addWidget(self.label_38, 0, 2, 1, 2)
        self.label_37 = QtWidgets.QLabel(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_37.sizePolicy().hasHeightForWidth())
        self.label_37.setSizePolicy(sizePolicy)
        self.label_37.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_37.setFont(font)
        self.label_37.setAlignment(QtCore.Qt.AlignCenter)
        self.label_37.setObjectName("label_37")
        self.gridLayout_8.addWidget(self.label_37, 0, 0, 1, 2)
        self.gridLayout_9.addLayout(self.gridLayout_8, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.tab_3)
        self.gridLayout_12.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.gridLayout_11 = QtWidgets.QGridLayout()
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.label_42 = QtWidgets.QLabel(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_42.sizePolicy().hasHeightForWidth())
        self.label_42.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_42.setFont(font)
        self.label_42.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_42.setObjectName("label_42")
        self.gridLayout_11.addWidget(self.label_42, 2, 0, 1, 1)
        self.TBButton = QtWidgets.QPushButton(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TBButton.sizePolicy().hasHeightForWidth())
        self.TBButton.setSizePolicy(sizePolicy)
        self.TBButton.setObjectName("TBButton")
        self.gridLayout_11.addWidget(self.TBButton, 1, 4, 1, 1)
        self.FocusGoTo = QtWidgets.QPushButton(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.FocusGoTo.sizePolicy().hasHeightForWidth())
        self.FocusGoTo.setSizePolicy(sizePolicy)
        self.FocusGoTo.setMaximumSize(QtCore.QSize(300, 16777215))
        self.FocusGoTo.setObjectName("FocusGoTo")
        self.gridLayout_11.addWidget(self.FocusGoTo, 4, 1, 1, 1)
        self.label_44 = QtWidgets.QLabel(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_44.sizePolicy().hasHeightForWidth())
        self.label_44.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_44.setFont(font)
        self.label_44.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_44.setObjectName("label_44")
        self.gridLayout_11.addWidget(self.label_44, 3, 0, 1, 1)
        self.label_39 = QtWidgets.QLabel(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_39.sizePolicy().hasHeightForWidth())
        self.label_39.setSizePolicy(sizePolicy)
        self.label_39.setMinimumSize(QtCore.QSize(0, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_39.setFont(font)
        self.label_39.setAlignment(QtCore.Qt.AlignCenter)
        self.label_39.setObjectName("label_39")
        self.gridLayout_11.addWidget(self.label_39, 0, 1, 1, 1)
        self.label_40 = QtWidgets.QLabel(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_40.sizePolicy().hasHeightForWidth())
        self.label_40.setSizePolicy(sizePolicy)
        self.label_40.setMinimumSize(QtCore.QSize(0, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_40.setFont(font)
        self.label_40.setAlignment(QtCore.Qt.AlignCenter)
        self.label_40.setObjectName("label_40")
        self.gridLayout_11.addWidget(self.label_40, 0, 2, 1, 1)
        self.label_43 = QtWidgets.QLabel(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_43.sizePolicy().hasHeightForWidth())
        self.label_43.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_43.setFont(font)
        self.label_43.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_43.setObjectName("label_43")
        self.gridLayout_11.addWidget(self.label_43, 1, 0, 1, 1)
        self.HButton = QtWidgets.QPushButton(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.HButton.sizePolicy().hasHeightForWidth())
        self.HButton.setSizePolicy(sizePolicy)
        self.HButton.setObjectName("HButton")
        self.gridLayout_11.addWidget(self.HButton, 2, 4, 1, 1)
        self.BlankButton = QtWidgets.QPushButton(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BlankButton.sizePolicy().hasHeightForWidth())
        self.BlankButton.setSizePolicy(sizePolicy)
        self.BlankButton.setObjectName("BlankButton")
        self.gridLayout_11.addWidget(self.BlankButton, 3, 4, 1, 1)
        self.label_41 = QtWidgets.QLabel(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_41.sizePolicy().hasHeightForWidth())
        self.label_41.setSizePolicy(sizePolicy)
        self.label_41.setMinimumSize(QtCore.QSize(0, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_41.setFont(font)
        self.label_41.setAlignment(QtCore.Qt.AlignCenter)
        self.label_41.setObjectName("label_41")
        self.gridLayout_11.addWidget(self.label_41, 0, 3, 1, 1)
        self.FocusHome = QtWidgets.QPushButton(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.FocusHome.sizePolicy().hasHeightForWidth())
        self.FocusHome.setSizePolicy(sizePolicy)
        self.FocusHome.setMaximumSize(QtCore.QSize(300, 16777215))
        self.FocusHome.setObjectName("FocusHome")
        self.gridLayout_11.addWidget(self.FocusHome, 5, 1, 1, 1)
        self.FilterGoTo = QtWidgets.QPushButton(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.FilterGoTo.sizePolicy().hasHeightForWidth())
        self.FilterGoTo.setSizePolicy(sizePolicy)
        self.FilterGoTo.setMaximumSize(QtCore.QSize(300, 16777215))
        self.FilterGoTo.setObjectName("FilterGoTo")
        self.gridLayout_11.addWidget(self.FilterGoTo, 4, 2, 1, 1)
        self.FilterHome = QtWidgets.QPushButton(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.FilterHome.sizePolicy().hasHeightForWidth())
        self.FilterHome.setSizePolicy(sizePolicy)
        self.FilterHome.setMaximumSize(QtCore.QSize(300, 16777215))
        self.FilterHome.setObjectName("FilterHome")
        self.gridLayout_11.addWidget(self.FilterHome, 5, 2, 1, 1)
        self.GratingGoTo = QtWidgets.QPushButton(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.GratingGoTo.sizePolicy().hasHeightForWidth())
        self.GratingGoTo.setSizePolicy(sizePolicy)
        self.GratingGoTo.setMaximumSize(QtCore.QSize(300, 16777215))
        self.GratingGoTo.setObjectName("GratingGoTo")
        self.gridLayout_11.addWidget(self.GratingGoTo, 4, 3, 1, 1)
        self.GratingHome = QtWidgets.QPushButton(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.GratingHome.sizePolicy().hasHeightForWidth())
        self.GratingHome.setSizePolicy(sizePolicy)
        self.GratingHome.setMaximumSize(QtCore.QSize(300, 16777215))
        self.GratingHome.setObjectName("GratingHome")
        self.gridLayout_11.addWidget(self.GratingHome, 5, 3, 1, 1)
        self.FocusStop = QtWidgets.QPushButton(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.FocusStop.sizePolicy().hasHeightForWidth())
        self.FocusStop.setSizePolicy(sizePolicy)
        self.FocusStop.setMaximumSize(QtCore.QSize(300, 16777215))
        self.FocusStop.setObjectName("FocusStop")
        self.gridLayout_11.addWidget(self.FocusStop, 6, 1, 1, 1)
        self.FilterStop = QtWidgets.QPushButton(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.FilterStop.sizePolicy().hasHeightForWidth())
        self.FilterStop.setSizePolicy(sizePolicy)
        self.FilterStop.setMaximumSize(QtCore.QSize(300, 16777215))
        self.FilterStop.setObjectName("FilterStop")
        self.gridLayout_11.addWidget(self.FilterStop, 6, 2, 1, 1)
        self.GratingStop = QtWidgets.QPushButton(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.GratingStop.sizePolicy().hasHeightForWidth())
        self.GratingStop.setSizePolicy(sizePolicy)
        self.GratingStop.setMaximumSize(QtCore.QSize(300, 16777215))
        self.GratingStop.setObjectName("GratingStop")
        self.gridLayout_11.addWidget(self.GratingStop, 6, 3, 1, 1)
        self.FocusStep = QtWidgets.QLineEdit(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.FocusStep.sizePolicy().hasHeightForWidth())
        self.FocusStep.setSizePolicy(sizePolicy)
        self.FocusStep.setObjectName("FocusStep")
        self.gridLayout_11.addWidget(self.FocusStep, 3, 1, 1, 1)
        self.FilterStep = QtWidgets.QLineEdit(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.FilterStep.sizePolicy().hasHeightForWidth())
        self.FilterStep.setSizePolicy(sizePolicy)
        self.FilterStep.setObjectName("FilterStep")
        self.gridLayout_11.addWidget(self.FilterStep, 3, 2, 1, 1)
        self.GratingStep = QtWidgets.QLineEdit(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.GratingStep.sizePolicy().hasHeightForWidth())
        self.GratingStep.setSizePolicy(sizePolicy)
        self.GratingStep.setObjectName("GratingStep")
        self.gridLayout_11.addWidget(self.GratingStep, 3, 3, 1, 1)
        self.FocusStatus = QtWidgets.QLabel(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.FocusStatus.sizePolicy().hasHeightForWidth())
        self.FocusStatus.setSizePolicy(sizePolicy)
        self.FocusStatus.setAlignment(QtCore.Qt.AlignCenter)
        self.FocusStatus.setObjectName("FocusStatus")
        self.gridLayout_11.addWidget(self.FocusStatus, 1, 1, 1, 1)
        self.FocusPosition = QtWidgets.QLabel(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.FocusPosition.sizePolicy().hasHeightForWidth())
        self.FocusPosition.setSizePolicy(sizePolicy)
        self.FocusPosition.setAlignment(QtCore.Qt.AlignCenter)
        self.FocusPosition.setObjectName("FocusPosition")
        self.gridLayout_11.addWidget(self.FocusPosition, 2, 1, 1, 1)
        self.FilterStatus = QtWidgets.QLabel(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.FilterStatus.sizePolicy().hasHeightForWidth())
        self.FilterStatus.setSizePolicy(sizePolicy)
        self.FilterStatus.setAlignment(QtCore.Qt.AlignCenter)
        self.FilterStatus.setObjectName("FilterStatus")
        self.gridLayout_11.addWidget(self.FilterStatus, 1, 2, 1, 1)
        self.FilterPosition = QtWidgets.QLabel(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.FilterPosition.sizePolicy().hasHeightForWidth())
        self.FilterPosition.setSizePolicy(sizePolicy)
        self.FilterPosition.setAlignment(QtCore.Qt.AlignCenter)
        self.FilterPosition.setObjectName("FilterPosition")
        self.gridLayout_11.addWidget(self.FilterPosition, 2, 2, 1, 1)
        self.GratingStatus = QtWidgets.QLabel(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.GratingStatus.sizePolicy().hasHeightForWidth())
        self.GratingStatus.setSizePolicy(sizePolicy)
        self.GratingStatus.setAlignment(QtCore.Qt.AlignCenter)
        self.GratingStatus.setObjectName("GratingStatus")
        self.gridLayout_11.addWidget(self.GratingStatus, 1, 3, 1, 1)
        self.GratingPosition = QtWidgets.QLabel(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.GratingPosition.sizePolicy().hasHeightForWidth())
        self.GratingPosition.setSizePolicy(sizePolicy)
        self.GratingPosition.setAlignment(QtCore.Qt.AlignCenter)
        self.GratingPosition.setObjectName("GratingPosition")
        self.gridLayout_11.addWidget(self.GratingPosition, 2, 3, 1, 1)
        self.gridLayout_12.addLayout(self.gridLayout_11, 0, 1, 1, 1)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.tab_4)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.gridLayout_13 = QtWidgets.QGridLayout()
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.GuiderExpTime = QtWidgets.QLineEdit(self.tab_4)
        self.GuiderExpTime.setObjectName("GuiderExpTime")
        self.gridLayout_13.addWidget(self.GuiderExpTime, 0, 1, 1, 1)
        self.CalibModeButton = QtWidgets.QPushButton(self.tab_4)
        self.CalibModeButton.setObjectName("CalibModeButton")
        self.gridLayout_13.addWidget(self.CalibModeButton, 1, 1, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.tab_4)
        self.label_11.setObjectName("label_11")
        self.gridLayout_13.addWidget(self.label_11, 0, 0, 1, 1)
        self.label_45 = QtWidgets.QLabel(self.tab_4)
        self.label_45.setObjectName("label_45")
        self.gridLayout_13.addWidget(self.label_45, 1, 0, 1, 1)
        self.ObsModeButton = QtWidgets.QPushButton(self.tab_4)
        self.ObsModeButton.setObjectName("ObsModeButton")
        self.gridLayout_13.addWidget(self.ObsModeButton, 1, 2, 1, 1)
        self.ArclampModeButton = QtWidgets.QPushButton(self.tab_4)
        self.ArclampModeButton.setObjectName("ArclampModeButton")
        self.gridLayout_13.addWidget(self.ArclampModeButton, 2, 1, 1, 1)
        self.ISphereModeButton = QtWidgets.QPushButton(self.tab_4)
        self.ISphereModeButton.setObjectName("ISphereModeButton")
        self.gridLayout_13.addWidget(self.ISphereModeButton, 2, 2, 1, 1)
        self.label_46 = QtWidgets.QLabel(self.tab_4)
        self.label_46.setObjectName("label_46")
        self.gridLayout_13.addWidget(self.label_46, 2, 0, 1, 1)
        self.FocusTestStop = QtWidgets.QPushButton(self.tab_4)
        self.FocusTestStop.setObjectName("FocusTestStop")
        self.gridLayout_13.addWidget(self.FocusTestStop, 3, 2, 1, 1)
        self.FocusTestButton = QtWidgets.QPushButton(self.tab_4)
        self.FocusTestButton.setObjectName("FocusTestButton")
        self.gridLayout_13.addWidget(self.FocusTestButton, 3, 1, 1, 1)
        self.label_47 = QtWidgets.QLabel(self.tab_4)
        self.label_47.setObjectName("label_47")
        self.gridLayout_13.addWidget(self.label_47, 4, 0, 1, 1)
        self.ForceIISEntry = QtWidgets.QLineEdit(self.tab_4)
        self.ForceIISEntry.setObjectName("ForceIISEntry")
        self.gridLayout_13.addWidget(self.ForceIISEntry, 4, 1, 1, 1)
        self.gridLayout_14.addLayout(self.gridLayout_13, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_4, "")
        self.horizontalLayout_3.addWidget(self.tabWidget)
        self.gridLayout_10.addLayout(self.horizontalLayout_3, 1, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(0, 0))
        self.label.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout_10.addWidget(self.label, 0, 0, 1, 1)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_10.addWidget(self.line, 2, 0, 1, 1)
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.SaveImageButton = QtWidgets.QPushButton(self.centralwidget)
        self.SaveImageButton.setObjectName("SaveImageButton")
        self.gridLayout_6.addWidget(self.SaveImageButton, 3, 6, 1, 1)
        self.line_5 = QtWidgets.QFrame(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.line_5.setFont(font)
        self.line_5.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.gridLayout_6.addWidget(self.line_5, 3, 3, 4, 1)
        self.SetTempButton = QtWidgets.QPushButton(self.centralwidget)
        self.SetTempButton.setObjectName("SetTempButton")
        self.gridLayout_6.addWidget(self.SetTempButton, 6, 6, 1, 1)
        self.label_26 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_26.setFont(font)
        self.label_26.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_26.setObjectName("label_26")
        self.gridLayout_6.addWidget(self.label_26, 3, 4, 1, 1)
        self.TakeImageButton = QtWidgets.QPushButton(self.centralwidget)
        self.TakeImageButton.setObjectName("TakeImageButton")
        self.gridLayout_6.addWidget(self.TakeImageButton, 3, 7, 1, 1)
        self.CentroidButton = QtWidgets.QPushButton(self.centralwidget)
        self.CentroidButton.setObjectName("CentroidButton")
        self.gridLayout_6.addWidget(self.CentroidButton, 5, 6, 1, 1)
        self.label_33 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_33.sizePolicy().hasHeightForWidth())
        self.label_33.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_33.setFont(font)
        self.label_33.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_33.setObjectName("label_33")
        self.gridLayout_6.addWidget(self.label_33, 4, 4, 1, 1)
        self.ExpType = QtWidgets.QComboBox(self.centralwidget)
        self.ExpType.setObjectName("ExpType")
        self.ExpType.addItem("")
        self.ExpType.addItem("")
        self.gridLayout_6.addWidget(self.ExpType, 3, 5, 1, 1)
        self.StopGuidingButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.StopGuidingButton.sizePolicy().hasHeightForWidth())
        self.StopGuidingButton.setSizePolicy(sizePolicy)
        self.StopGuidingButton.setObjectName("StopGuidingButton")
        self.gridLayout_6.addWidget(self.StopGuidingButton, 5, 7, 1, 1)
        self.ExpTime = QtWidgets.QLineEdit(self.centralwidget)
        self.ExpTime.setObjectName("ExpTime")
        self.gridLayout_6.addWidget(self.ExpTime, 4, 5, 1, 1)
        self.FocStep = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.FocStep.sizePolicy().hasHeightForWidth())
        self.FocStep.setSizePolicy(sizePolicy)
        self.FocStep.setObjectName("FocStep")
        self.gridLayout_6.addWidget(self.FocStep, 5, 2, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.BKWButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BKWButton.sizePolicy().hasHeightForWidth())
        self.BKWButton.setSizePolicy(sizePolicy)
        self.BKWButton.setMinimumSize(QtCore.QSize(30, 0))
        self.BKWButton.setMaximumSize(QtCore.QSize(100, 16777215))
        self.BKWButton.setObjectName("BKWButton")
        self.horizontalLayout.addWidget(self.BKWButton)
        self.FWDButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.FWDButton.sizePolicy().hasHeightForWidth())
        self.FWDButton.setSizePolicy(sizePolicy)
        self.FWDButton.setMinimumSize(QtCore.QSize(30, 0))
        self.FWDButton.setMaximumSize(QtCore.QSize(100, 16777215))
        self.FWDButton.setObjectName("FWDButton")
        self.horizontalLayout.addWidget(self.FWDButton)
        self.gridLayout_6.addLayout(self.horizontalLayout, 6, 2, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_23.sizePolicy().hasHeightForWidth())
        self.label_23.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_23.setFont(font)
        self.label_23.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_23.setObjectName("label_23")
        self.gridLayout_6.addWidget(self.label_23, 4, 1, 1, 1)
        self.FocPosition = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.FocPosition.sizePolicy().hasHeightForWidth())
        self.FocPosition.setSizePolicy(sizePolicy)
        self.FocPosition.setObjectName("FocPosition")
        self.gridLayout_6.addWidget(self.FocPosition, 4, 2, 1, 1)
        self.FilterVal = QtWidgets.QComboBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.FilterVal.sizePolicy().hasHeightForWidth())
        self.FilterVal.setSizePolicy(sizePolicy)
        self.FilterVal.setObjectName("FilterVal")
        self.FilterVal.addItem("")
        self.FilterVal.addItem("")
        self.FilterVal.addItem("")
        self.FilterVal.addItem("")
        self.FilterVal.addItem("")
        self.gridLayout_6.addWidget(self.FilterVal, 3, 2, 1, 1)
        self.label_28 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_28.setFont(font)
        self.label_28.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_28.setObjectName("label_28")
        self.gridLayout_6.addWidget(self.label_28, 6, 4, 1, 1)
        self.StartGuidingButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.StartGuidingButton.sizePolicy().hasHeightForWidth())
        self.StartGuidingButton.setSizePolicy(sizePolicy)
        self.StartGuidingButton.setObjectName("StartGuidingButton")
        self.gridLayout_6.addWidget(self.StartGuidingButton, 4, 7, 1, 1)
        self.FocusCameraButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.FocusCameraButton.sizePolicy().hasHeightForWidth())
        self.FocusCameraButton.setSizePolicy(sizePolicy)
        self.FocusCameraButton.setObjectName("FocusCameraButton")
        self.gridLayout_6.addWidget(self.FocusCameraButton, 4, 6, 1, 1)
        self.label_27 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_27.setFont(font)
        self.label_27.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_27.setObjectName("label_27")
        self.gridLayout_6.addWidget(self.label_27, 5, 4, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_24.setFont(font)
        self.label_24.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_24.setObjectName("label_24")
        self.gridLayout_6.addWidget(self.label_24, 5, 1, 1, 1)
        self.CCDTemp = QtWidgets.QLabel(self.centralwidget)
        self.CCDTemp.setObjectName("CCDTemp")
        self.gridLayout_6.addWidget(self.CCDTemp, 5, 5, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_22.setFont(font)
        self.label_22.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_22.setObjectName("label_22")
        self.gridLayout_6.addWidget(self.label_22, 3, 1, 1, 1)
        self.SetTempValue = QtWidgets.QLineEdit(self.centralwidget)
        self.SetTempValue.setObjectName("SetTempValue")
        self.gridLayout_6.addWidget(self.SetTempValue, 6, 5, 1, 1)
        self.label_29 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_29.sizePolicy().hasHeightForWidth())
        self.label_29.setSizePolicy(sizePolicy)
        self.label_29.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_29.setFont(font)
        self.label_29.setAlignment(QtCore.Qt.AlignCenter)
        self.label_29.setObjectName("label_29")
        self.gridLayout_6.addWidget(self.label_29, 2, 1, 1, 7)
        self.GuidingText = QtWidgets.QTextEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.GuidingText.sizePolicy().hasHeightForWidth())
        self.GuidingText.setSizePolicy(sizePolicy)
        self.GuidingText.setMinimumSize(QtCore.QSize(250, 0))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(10)
        font.setItalic(True)
        self.GuidingText.setFont(font)
        self.GuidingText.setObjectName("GuidingText")
        self.gridLayout_6.addWidget(self.GuidingText, 2, 8, 5, 1)
        self.gridLayout_10.addLayout(self.gridLayout_6, 7, 0, 1, 1)
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.line_3.setFont(font)
        self.line_3.setAutoFillBackground(False)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout_10.addWidget(self.line_3, 6, 0, 1, 1)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_12.sizePolicy().hasHeightForWidth())
        self.label_12.setSizePolicy(sizePolicy)
        self.label_12.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.gridLayout_3.addWidget(self.label_12, 0, 0, 1, 8)
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_15.setObjectName("label_15")
        self.gridLayout_3.addWidget(self.label_15, 2, 0, 1, 1)
        self.label_32 = QtWidgets.QLabel(self.centralwidget)
        self.label_32.setAlignment(QtCore.Qt.AlignCenter)
        self.label_32.setObjectName("label_32")
        self.gridLayout_3.addWidget(self.label_32, 3, 6, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.centralwidget)
        self.label_16.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_16.setObjectName("label_16")
        self.gridLayout_3.addWidget(self.label_16, 3, 0, 1, 1)
        self.line_6 = QtWidgets.QFrame(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.line_6.setFont(font)
        self.line_6.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.gridLayout_3.addWidget(self.line_6, 1, 5, 3, 1)
        self.label_17 = QtWidgets.QLabel(self.centralwidget)
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setObjectName("label_17")
        self.gridLayout_3.addWidget(self.label_17, 1, 3, 1, 1)
        self.SetNextButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SetNextButton.sizePolicy().hasHeightForWidth())
        self.SetNextButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setStrikeOut(True)
        self.SetNextButton.setFont(font)
        self.SetNextButton.setDefault(False)
        self.SetNextButton.setFlat(False)
        self.SetNextButton.setObjectName("SetNextButton")
        self.gridLayout_3.addWidget(self.SetNextButton, 2, 2, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_14.setObjectName("label_14")
        self.gridLayout_3.addWidget(self.label_14, 1, 0, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.centralwidget)
        self.label_19.setAlignment(QtCore.Qt.AlignCenter)
        self.label_19.setObjectName("label_19")
        self.gridLayout_3.addWidget(self.label_19, 3, 3, 1, 1)
        self.NodSelection = QtWidgets.QComboBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.NodSelection.sizePolicy().hasHeightForWidth())
        self.NodSelection.setSizePolicy(sizePolicy)
        self.NodSelection.setObjectName("NodSelection")
        self.NodSelection.addItem("")
        self.NodSelection.addItem("")
        self.gridLayout_3.addWidget(self.NodSelection, 1, 7, 1, 1)
        self.label_31 = QtWidgets.QLabel(self.centralwidget)
        self.label_31.setAlignment(QtCore.Qt.AlignCenter)
        self.label_31.setObjectName("label_31")
        self.gridLayout_3.addWidget(self.label_31, 2, 6, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.OffsetNod = QtWidgets.QRadioButton(self.centralwidget)
        self.OffsetNod.setChecked(True)
        self.OffsetNod.setObjectName("OffsetNod")
        self.verticalLayout.addWidget(self.OffsetNod)
        self.RADECNod = QtWidgets.QRadioButton(self.centralwidget)
        font = QtGui.QFont()
        font.setStrikeOut(True)
        self.RADECNod.setFont(font)
        self.RADECNod.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.RADECNod.setChecked(False)
        self.RADECNod.setObjectName("RADECNod")
        self.verticalLayout.addWidget(self.RADECNod)
        self.gridLayout_3.addLayout(self.verticalLayout, 3, 4, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.centralwidget)
        self.label_18.setAlignment(QtCore.Qt.AlignCenter)
        self.label_18.setObjectName("label_18")
        self.gridLayout_3.addWidget(self.label_18, 2, 3, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.centralwidget)
        self.label_25.setAlignment(QtCore.Qt.AlignCenter)
        self.label_25.setObjectName("label_25")
        self.gridLayout_3.addWidget(self.label_25, 1, 6, 1, 1)
        self.ObjText = QtWidgets.QLineEdit(self.centralwidget)
        self.ObjText.setObjectName("ObjText")
        self.gridLayout_3.addWidget(self.ObjText, 1, 1, 1, 1)
        self.RAObj = QtWidgets.QLineEdit(self.centralwidget)
        self.RAObj.setObjectName("RAObj")
        self.gridLayout_3.addWidget(self.RAObj, 2, 1, 1, 1)
        self.DECObj = QtWidgets.QLineEdit(self.centralwidget)
        self.DECObj.setObjectName("DECObj")
        self.gridLayout_3.addWidget(self.DECObj, 3, 1, 1, 1)
        self.NodRAText = QtWidgets.QLineEdit(self.centralwidget)
        self.NodRAText.setObjectName("NodRAText")
        self.gridLayout_3.addWidget(self.NodRAText, 1, 4, 1, 1)
        self.NodDecText = QtWidgets.QLineEdit(self.centralwidget)
        self.NodDecText.setObjectName("NodDecText")
        self.gridLayout_3.addWidget(self.NodDecText, 2, 4, 1, 1)
        self.NNods = QtWidgets.QLineEdit(self.centralwidget)
        self.NNods.setObjectName("NNods")
        self.gridLayout_3.addWidget(self.NNods, 2, 7, 1, 1)
        self.NodsPerCal = QtWidgets.QLineEdit(self.centralwidget)
        self.NodsPerCal.setObjectName("NodsPerCal")
        self.gridLayout_3.addWidget(self.NodsPerCal, 3, 7, 1, 1)
        self.SkyCheckBox = QtWidgets.QCheckBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SkyCheckBox.sizePolicy().hasHeightForWidth())
        self.SkyCheckBox.setSizePolicy(sizePolicy)
        self.SkyCheckBox.setObjectName("SkyCheckBox")
        self.gridLayout_3.addWidget(self.SkyCheckBox, 1, 2, 1, 1)
        self.gridLayout_10.addLayout(self.gridLayout_3, 3, 0, 1, 1)
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout_10.addWidget(self.line_2, 4, 0, 1, 1)
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.DetectorStatusLabel = QtWidgets.QLabel(self.centralwidget)
        self.DetectorStatusLabel.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DetectorStatusLabel.sizePolicy().hasHeightForWidth())
        self.DetectorStatusLabel.setSizePolicy(sizePolicy)
        self.DetectorStatusLabel.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.DetectorStatusLabel.setFont(font)
        self.DetectorStatusLabel.setAutoFillBackground(False)
        self.DetectorStatusLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.DetectorStatusLabel.setObjectName("DetectorStatusLabel")
        self.gridLayout_5.addWidget(self.DetectorStatusLabel, 2, 3, 1, 1)
        self.NodBeginButton = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.NodBeginButton.setFont(font)
        self.NodBeginButton.setObjectName("NodBeginButton")
        self.gridLayout_5.addWidget(self.NodBeginButton, 2, 4, 1, 1)
        self.ExposureButton = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.ExposureButton.setFont(font)
        self.ExposureButton.setObjectName("ExposureButton")
        self.gridLayout_5.addWidget(self.ExposureButton, 1, 4, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_13.sizePolicy().hasHeightForWidth())
        self.label_13.setSizePolicy(sizePolicy)
        self.label_13.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setAutoFillBackground(False)
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.gridLayout_5.addWidget(self.label_13, 0, 0, 1, 5)
        self.NRampsText = QtWidgets.QLineEdit(self.centralwidget)
        self.NRampsText.setObjectName("NRampsText")
        self.gridLayout_5.addWidget(self.NRampsText, 1, 1, 1, 1)
        self.NReadsText = QtWidgets.QLineEdit(self.centralwidget)
        self.NReadsText.setObjectName("NReadsText")
        self.gridLayout_5.addWidget(self.NReadsText, 2, 1, 1, 1)
        self.label_30 = QtWidgets.QLabel(self.centralwidget)
        self.label_30.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_30.setObjectName("label_30")
        self.gridLayout_5.addWidget(self.label_30, 3, 0, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.centralwidget)
        self.label_21.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_21.setObjectName("label_21")
        self.gridLayout_5.addWidget(self.label_21, 2, 0, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.centralwidget)
        self.label_20.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_20.setObjectName("label_20")
        self.gridLayout_5.addWidget(self.label_20, 1, 0, 1, 1)
        self.label_34 = QtWidgets.QLabel(self.centralwidget)
        self.label_34.setAlignment(QtCore.Qt.AlignCenter)
        self.label_34.setObjectName("label_34")
        self.gridLayout_5.addWidget(self.label_34, 1, 2, 1, 1)
        self.ExpTypeSelect = QtWidgets.QComboBox(self.centralwidget)
        self.ExpTypeSelect.setObjectName("ExpTypeSelect")
        self.ExpTypeSelect.addItem("")
        self.ExpTypeSelect.addItem("")
        self.ExpTypeSelect.addItem("")
        self.ExpTypeSelect.addItem("")
        self.ExpTypeSelect.addItem("")
        self.gridLayout_5.addWidget(self.ExpTypeSelect, 1, 3, 1, 1)
        self.TakeCalibButton = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.TakeCalibButton.setFont(font)
        self.TakeCalibButton.setObjectName("TakeCalibButton")
        self.gridLayout_5.addWidget(self.TakeCalibButton, 2, 2, 1, 1)
        self.ExpProgressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.ExpProgressBar.setProperty("value", 24)
        self.ExpProgressBar.setObjectName("ExpProgressBar")
        self.gridLayout_5.addWidget(self.ExpProgressBar, 3, 1, 1, 3)
        self.StopExpButton = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.StopExpButton.setFont(font)
        self.StopExpButton.setObjectName("StopExpButton")
        self.gridLayout_5.addWidget(self.StopExpButton, 3, 4, 1, 1)
        self.OutputText = QtWidgets.QTextEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(10)
        font.setItalic(True)
        self.OutputText.setFont(font)
        self.OutputText.setOverwriteMode(False)
        self.OutputText.setObjectName("OutputText")
        self.gridLayout_5.addWidget(self.OutputText, 0, 5, 4, 1)
        self.gridLayout_10.addLayout(self.gridLayout_5, 5, 0, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_10, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 980, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuInitialie = QtWidgets.QMenu(self.menubar)
        self.menuInitialie.setObjectName("menuInitialie")
        MainWindow.setMenuBar(self.menubar)
        self.actionConnect = QtWidgets.QAction(MainWindow)
        self.actionConnect.setObjectName("actionConnect")
        self.actionInitialize = QtWidgets.QAction(MainWindow)
        self.actionInitialize.setObjectName("actionInitialize")
        self.actionDisconnect = QtWidgets.QAction(MainWindow)
        self.actionDisconnect.setObjectName("actionDisconnect")
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.actionCalc_Offset = QtWidgets.QAction(MainWindow)
        self.actionCalc_Offset.setObjectName("actionCalc_Offset")
        self.menuFile.addAction(self.actionQuit)
        self.menuInitialie.addAction(self.actionConnect)
        self.menuInitialie.addAction(self.actionInitialize)
        self.menuInitialie.addAction(self.actionDisconnect)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuInitialie.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "RA:"))
        self.IISLabel.setText(_translate("MainWindow", "TextLabel"))
        self.label_5.setText(_translate("MainWindow", "EL:"))
        self.RALabel.setText(_translate("MainWindow", "TextLabel"))
        self.DECLabel.setText(_translate("MainWindow", "TextLabel"))
        self.HALabel.setText(_translate("MainWindow", "TextLabel"))
        self.label_10.setText(_translate("MainWindow", "Telescope Parameters"))
        self.ELLabel.setText(_translate("MainWindow", "TextLabel"))
        self.label_6.setText(_translate("MainWindow", "IIS:"))
        self.AZLabel.setText(_translate("MainWindow", "TextLabel"))
        self.label_7.setText(_translate("MainWindow", "HA:"))
        self.label_4.setText(_translate("MainWindow", "AZ:"))
        self.label_3.setText(_translate("MainWindow", "DEC:"))
        self.label_9.setText(_translate("MainWindow", "DEC Move (\")"))
        self.label_36.setText(_translate("MainWindow", "X Pos"))
        self.label_8.setText(_translate("MainWindow", "RA Move (\")"))
        self.WIFISMoveButton.setText(_translate("MainWindow", "Move to WIFIS"))
        self.label_35.setText(_translate("MainWindow", "Y Pos"))
        self.MoveBackButton.setText(_translate("MainWindow", "Move Back"))
        self.CalOffsetButton.setText(_translate("MainWindow", "Calc Offset"))
        self.RAMoveBox.setText(_translate("MainWindow", "0"))
        self.GuiderMoveButton.setText(_translate("MainWindow", "Move To Guider"))
        self.YPos.setText(_translate("MainWindow", "0"))
        self.moveTelescopeButton.setText(_translate("MainWindow", "Move Telescope"))
        self.XPos.setText(_translate("MainWindow", "0"))
        self.DECMoveBox.setText(_translate("MainWindow", "0"))
        self.CenteringCheck.setText(_translate("MainWindow", "Centering Check"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Telescope Control"))
        self.Power15.setText(_translate("MainWindow", "PushButton"))
        self.Power23.setText(_translate("MainWindow", "PushButton"))
        self.Power24.setText(_translate("MainWindow", "PushButton"))
        self.Power27.setText(_translate("MainWindow", "PushButton"))
        self.Power11.setText(_translate("MainWindow", "PushButton"))
        self.Power13.setText(_translate("MainWindow", "PushButton"))
        self.Power12.setText(_translate("MainWindow", "PushButton"))
        self.Power17.setText(_translate("MainWindow", "PushButton"))
        self.Power25.setText(_translate("MainWindow", "PushButton"))
        self.Power22.setText(_translate("MainWindow", "PushButton"))
        self.Power26.setText(_translate("MainWindow", "PushButton"))
        self.Power28.setText(_translate("MainWindow", "PushButton"))
        self.Power21.setText(_translate("MainWindow", "PushButton"))
        self.Power16.setText(_translate("MainWindow", "PushButton"))
        self.Power18.setText(_translate("MainWindow", "PushButton"))
        self.Power14.setText(_translate("MainWindow", "PushButton"))
        self.label_38.setText(_translate("MainWindow", "Power Bar 2"))
        self.label_37.setText(_translate("MainWindow", "Power Bar 1"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Power Control"))
        self.label_42.setText(_translate("MainWindow", "Position"))
        self.TBButton.setText(_translate("MainWindow", "TB Filter"))
        self.FocusGoTo.setText(_translate("MainWindow", "GoTo"))
        self.label_44.setText(_translate("MainWindow", "Go To:"))
        self.label_39.setText(_translate("MainWindow", "Focus Motor (1)"))
        self.label_40.setText(_translate("MainWindow", "Filter Motor (2)"))
        self.label_43.setText(_translate("MainWindow", "Status"))
        self.HButton.setText(_translate("MainWindow", "H Filter"))
        self.BlankButton.setText(_translate("MainWindow", "Blank Filter"))
        self.label_41.setText(_translate("MainWindow", "Grating Motor (3)"))
        self.FocusHome.setText(_translate("MainWindow", "Home"))
        self.FilterGoTo.setText(_translate("MainWindow", "GoTo"))
        self.FilterHome.setText(_translate("MainWindow", "Home"))
        self.GratingGoTo.setText(_translate("MainWindow", "GoTo"))
        self.GratingHome.setText(_translate("MainWindow", "Home"))
        self.FocusStop.setText(_translate("MainWindow", "Stop"))
        self.FilterStop.setText(_translate("MainWindow", "Stop"))
        self.GratingStop.setText(_translate("MainWindow", "Stop"))
        self.FocusStep.setText(_translate("MainWindow", "-125"))
        self.FilterStep.setText(_translate("MainWindow", "20000"))
        self.GratingStep.setText(_translate("MainWindow", "-180"))
        self.FocusStatus.setText(_translate("MainWindow", "TextLabel"))
        self.FocusPosition.setText(_translate("MainWindow", "TextLabel"))
        self.FilterStatus.setText(_translate("MainWindow", "TextLabel"))
        self.FilterPosition.setText(_translate("MainWindow", "TextLabel"))
        self.GratingStatus.setText(_translate("MainWindow", "TextLabel"))
        self.GratingPosition.setText(_translate("MainWindow", "TextLabel"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Motor Control"))
        self.GuiderExpTime.setText(_translate("MainWindow", "1500"))
        self.CalibModeButton.setText(_translate("MainWindow", "Calibration Mode"))
        self.label_11.setText(_translate("MainWindow", "Guide ExpTime"))
        self.label_45.setText(_translate("MainWindow", "WIFIS Flipper"))
        self.ObsModeButton.setText(_translate("MainWindow", "Observation Mode"))
        self.ArclampModeButton.setText(_translate("MainWindow", "Arclamp"))
        self.ISphereModeButton.setText(_translate("MainWindow", "Integrating Sphere"))
        self.label_46.setText(_translate("MainWindow", "Calib Flipper"))
        self.FocusTestStop.setText(_translate("MainWindow", "Stop Focus Test"))
        self.FocusTestButton.setText(_translate("MainWindow", "Focus Test"))
        self.label_47.setText(_translate("MainWindow", "Force IIS"))
        self.ForceIISEntry.setText(_translate("MainWindow", "90"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "Additional Options"))
        self.label.setText(_translate("MainWindow", "WIFIS Control"))
        self.SaveImageButton.setText(_translate("MainWindow", "Save Image"))
        self.SetTempButton.setText(_translate("MainWindow", "Set Temp"))
        self.label_26.setText(_translate("MainWindow", "Exposure Type:"))
        self.TakeImageButton.setText(_translate("MainWindow", "Take Image"))
        self.CentroidButton.setText(_translate("MainWindow", "Centroid Stars"))
        self.label_33.setText(_translate("MainWindow", "Exposure Time (ms):"))
        self.ExpType.setCurrentText(_translate("MainWindow", "Normal"))
        self.ExpType.setItemText(0, _translate("MainWindow", "Normal"))
        self.ExpType.setItemText(1, _translate("MainWindow", "Dark"))
        self.StopGuidingButton.setText(_translate("MainWindow", "Stop Guiding"))
        self.ExpTime.setText(_translate("MainWindow", "1500"))
        self.FocStep.setText(_translate("MainWindow", "100"))
        self.BKWButton.setText(_translate("MainWindow", "BWD"))
        self.FWDButton.setText(_translate("MainWindow", "FWD"))
        self.label_23.setText(_translate("MainWindow", "Focus Pos:"))
        self.FocPosition.setText(_translate("MainWindow", "TextLabel"))
        self.FilterVal.setCurrentText(_translate("MainWindow", "Z"))
        self.FilterVal.setItemText(0, _translate("MainWindow", "Z"))
        self.FilterVal.setItemText(1, _translate("MainWindow", "I"))
        self.FilterVal.setItemText(2, _translate("MainWindow", "R"))
        self.FilterVal.setItemText(3, _translate("MainWindow", "G"))
        self.FilterVal.setItemText(4, _translate("MainWindow", "H-Alpha"))
        self.label_28.setText(_translate("MainWindow", "Set CCD Temp"))
        self.StartGuidingButton.setText(_translate("MainWindow", "Start Guiding"))
        self.FocusCameraButton.setText(_translate("MainWindow", "Focus Camera"))
        self.label_27.setText(_translate("MainWindow", "CCD Temp:"))
        self.label_24.setText(_translate("MainWindow", "Focus Step:"))
        self.CCDTemp.setText(_translate("MainWindow", "TextLabel"))
        self.label_22.setText(_translate("MainWindow", "Filter:"))
        self.SetTempValue.setText(_translate("MainWindow", "-20"))
        self.label_29.setText(_translate("MainWindow", "Guider Control"))
        self.label_12.setText(_translate("MainWindow", "Source Parameters"))
        self.label_15.setText(_translate("MainWindow", "RA Obj:"))
        self.label_32.setText(_translate("MainWindow", "Nods per Cal"))
        self.label_16.setText(_translate("MainWindow", "DEC Obj:"))
        self.label_17.setText(_translate("MainWindow", "Nod RA:"))
        self.SetNextButton.setText(_translate("MainWindow", "Set Object as Next"))
        self.label_14.setText(_translate("MainWindow", "Target:"))
        self.label_19.setText(_translate("MainWindow", "Nod Type:"))
        self.NodSelection.setItemText(0, _translate("MainWindow", "ABA"))
        self.NodSelection.setItemText(1, _translate("MainWindow", "AB"))
        self.label_31.setText(_translate("MainWindow", "N Nods"))
        self.OffsetNod.setText(_translate("MainWindow", "Offset (\")"))
        self.RADECNod.setText(_translate("MainWindow", "Pos RA/DEC"))
        self.label_18.setText(_translate("MainWindow", "Nod DEC:"))
        self.label_25.setText(_translate("MainWindow", "Nod Pattern"))
        self.NodRAText.setText(_translate("MainWindow", "0"))
        self.NodDecText.setText(_translate("MainWindow", "0"))
        self.NNods.setText(_translate("MainWindow", "3"))
        self.NodsPerCal.setText(_translate("MainWindow", "3"))
        self.SkyCheckBox.setText(_translate("MainWindow", "Sky"))
        self.DetectorStatusLabel.setText(_translate("MainWindow", "H2RG Not Connected"))
        self.NodBeginButton.setText(_translate("MainWindow", "BEGIN NOD SEQ"))
        self.ExposureButton.setText(_translate("MainWindow", "SINGLE EXPOSURE"))
        self.label_13.setText(_translate("MainWindow", "Exposure Control"))
        self.NRampsText.setText(_translate("MainWindow", "1"))
        self.NReadsText.setText(_translate("MainWindow", "5"))
        self.label_30.setText(_translate("MainWindow", "Exp Progress"))
        self.label_21.setText(_translate("MainWindow", "N Reads:"))
        self.label_20.setText(_translate("MainWindow", "N Ramps:"))
        self.label_34.setText(_translate("MainWindow", "Exposure Type:"))
        self.ExpTypeSelect.setItemText(0, _translate("MainWindow", "Ramp"))
        self.ExpTypeSelect.setItemText(1, _translate("MainWindow", "CDS"))
        self.ExpTypeSelect.setItemText(2, _translate("MainWindow", "Single Frame"))
        self.ExpTypeSelect.setItemText(3, _translate("MainWindow", "Arc Ramp"))
        self.ExpTypeSelect.setItemText(4, _translate("MainWindow", "Flat Ramp"))
        self.TakeCalibButton.setText(_translate("MainWindow", "Take Calibrations"))
        self.StopExpButton.setText(_translate("MainWindow", "STOP NODS"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuInitialie.setTitle(_translate("MainWindow", "H2RG"))
        self.actionConnect.setText(_translate("MainWindow", "Connect"))
        self.actionConnect.setToolTip(_translate("MainWindow", "Connect to H2RG Server"))
        self.actionInitialize.setText(_translate("MainWindow", "Initialize"))
        self.actionInitialize.setToolTip(_translate("MainWindow", "Initialize H2RG Detector"))
        self.actionDisconnect.setText(_translate("MainWindow", "Disconnect"))
        self.actionDisconnect.setToolTip(_translate("MainWindow", "Disconnect from H2RG Server"))
        self.actionQuit.setText(_translate("MainWindow", "Quit"))
        self.actionCalc_Offset.setText(_translate("MainWindow", "Calc Offset"))

