#!/bin/bash
while true
do
    scp  "/home/utopea/WIFIS-Team/wifiscontrol/monitor/t_stream.html" suresh@thor.dunlap.utoronto.ca:Sites/wifis/
    scp  /home/utopea/WIFIS-Team/wifiscontrol/monitor/*.jpg suresh@thor.dunlap.utoronto.ca:Sites/wifis/

    sleep 30
done
