#!/bin/bash
while true
do
    scp -i /home/utopea/.ssh/thor_rsa "/home/utopea/WIFIS-Team/wifiscontrol/monitor/t_stream.html" suresh@thor.dunlap.utoronto.ca:Sites/wifis/
    scp -i /home/utopea/.ssh/thor_rsa /home/utopea/WIFIS-Team/wifiscontrol/monitor/*.jpg suresh@thor.dunlap.utoronto.ca:Sites/wifis/
#    scp -i /home/utopea/.ssh/thor_rsa "/home/utopea/WIFIS-Team/controlcode/monitor/history_plot_heater.jpg" suresh@thor.dunlap.utoronto.ca:Sites/wifis/
#    scp -i /home/utopea/.ssh/thor_rsa "/home/utopea/WIFIS-Team/controlcode/monitor/history_plot_Tgrad.jpg" suresh@thor.dunlap.utoronto.ca:Sites/wifis/
#    scp -i /home/utopea/.ssh/thor_rsa "/home/utopea/WIFIS-Team/controlcode/monitor/pressure_plot.jpg" suresh@thor.dunlap.utoronto.ca:Sites/wifis/
#    scp -i /home/utopea/.ssh/thor_rsa "/home/utopea/WIFIS-Team/controlcode/monitor/Wed Nov 29 12-16-39" suresh@thor.dunlap.utoronto.ca:Dropbox/WIFIS-Electronics/temp_files/


    sleep 60
done
